// GENERATED by scripts/generate-admin1.mjs — do not edit by hand.
// Admin-1 regions from Natural Earth (public domain). Boundaries for these are
// served from public/regions-{cc}.geojson.
import type { RegionConfig } from "./countries";

export const GENERATED_REGIONS: Record<string, Record<string, RegionConfig>> = {
  "CA": {
    "AB": {
      "code": "CA-AB",
      "abbrev": "AB",
      "name": "Alberta",
      "bounds": [
        48.99,
        -120,
        60,
        -110
      ]
    },
    "BC": {
      "code": "CA-BC",
      "abbrev": "BC",
      "name": "British Columbia",
      "bounds": [
        48.32,
        -139.06,
        60,
        -114.05
      ]
    },
    "MB": {
      "code": "CA-MB",
      "abbrev": "MB",
      "name": "Manitoba",
      "bounds": [
        48.99,
        -102,
        60,
        -88.95
      ]
    },
    "NB": {
      "code": "CA-NB",
      "abbrev": "NB",
      "name": "New Brunswick",
      "bounds": [
        44.63,
        -69.05,
        48.07,
        -63.83
      ]
    },
    "NL": {
      "code": "CA-NL",
      "abbrev": "NL",
      "name": "Newfoundland and Labrador",
      "bounds": [
        46.63,
        -67.76,
        60.31,
        -52.65
      ]
    },
    "NS": {
      "code": "CA-NS",
      "abbrev": "NS",
      "name": "Nova Scotia",
      "bounds": [
        43.52,
        -66.32,
        47.01,
        -59.73
      ]
    },
    "NT": {
      "code": "CA-NT",
      "abbrev": "NT",
      "name": "Northwest Territories",
      "bounds": [
        60,
        -136.45,
        78.76,
        -101.99
      ]
    },
    "NU": {
      "code": "CA-NU",
      "abbrev": "NU",
      "name": "Nunavut",
      "bounds": [
        51.94,
        -120.68,
        83.12,
        -61.21
      ]
    },
    "ON": {
      "code": "CA-ON",
      "abbrev": "ON",
      "name": "Ontario",
      "bounds": [
        41.67,
        -95.16,
        56.85,
        -74.34
      ]
    },
    "PE": {
      "code": "CA-PE",
      "abbrev": "PE",
      "name": "Prince Edward Island",
      "bounds": [
        45.97,
        -64.4,
        47.06,
        -62.02
      ]
    },
    "QC": {
      "code": "CA-QC",
      "abbrev": "QC",
      "name": "Québec",
      "bounds": [
        45,
        -79.71,
        62.57,
        -57.1
      ]
    },
    "SK": {
      "code": "CA-SK",
      "abbrev": "SK",
      "name": "Saskatchewan",
      "bounds": [
        48.99,
        -110,
        60,
        -101.37
      ]
    },
    "YT": {
      "code": "CA-YT",
      "abbrev": "YT",
      "name": "Yukon",
      "bounds": [
        60,
        -141,
        69.65,
        -123.82
      ]
    }
  },
  "GB": {
    "EAST": {
      "code": "GB-EAST",
      "abbrev": "EAST",
      "name": "East",
      "bounds": [
        51.45,
        -0.73,
        52.99,
        1.77
      ]
    },
    "EASTMIDLANDS": {
      "code": "GB-EASTMIDLANDS",
      "abbrev": "EASTMIDLANDS",
      "name": "East Midlands",
      "bounds": [
        51.98,
        -2.02,
        53.61,
        0.36
      ]
    },
    "GREATERLONDON": {
      "code": "GB-GREATERLONDON",
      "abbrev": "GREATERLONDON",
      "name": "Greater London",
      "bounds": [
        51.28,
        -0.5,
        51.69,
        0.34
      ]
    },
    "NORTHEAST": {
      "code": "GB-NORTHEAST",
      "abbrev": "NORTHEAST",
      "name": "North East",
      "bounds": [
        54.44,
        -2.68,
        55.81,
        -0.78
      ]
    },
    "NORTHWEST": {
      "code": "GB-NORTHWEST",
      "abbrev": "NORTHWEST",
      "name": "North West",
      "bounds": [
        52.95,
        -3.63,
        55.19,
        -1.9
      ]
    },
    "NORTHERNIRELAND": {
      "code": "GB-NORTHERNIRELAND",
      "abbrev": "NORTHERNIRELAND",
      "name": "Northern Ireland",
      "bounds": [
        54.03,
        -8.17,
        55.31,
        -5.43
      ]
    },
    "SCOTLAND": {
      "code": "GB-SCOTLAND",
      "abbrev": "SCOTLAND",
      "name": "Scotland",
      "bounds": [
        54.63,
        -13.69,
        60.85,
        -0.75
      ]
    },
    "SOUTHEAST": {
      "code": "GB-SOUTHEAST",
      "abbrev": "SOUTHEAST",
      "name": "South East",
      "bounds": [
        50.58,
        -1.95,
        52.19,
        1.45
      ]
    },
    "SOUTHWEST": {
      "code": "GB-SOUTHWEST",
      "abbrev": "SOUTHWEST",
      "name": "South West",
      "bounds": [
        49.91,
        -6.35,
        52.11,
        -1.49
      ]
    },
    "WALES": {
      "code": "GB-WALES",
      "abbrev": "WALES",
      "name": "Wales",
      "bounds": [
        51.38,
        -5.31,
        53.43,
        -2.65
      ]
    },
    "WESTMIDLANDS": {
      "code": "GB-WESTMIDLANDS",
      "abbrev": "WESTMIDLANDS",
      "name": "West Midlands",
      "bounds": [
        51.82,
        -3.22,
        53.21,
        -1.17
      ]
    },
    "YORKSHIREANDTHEHUMBER": {
      "code": "GB-YORKSHIREANDTHEHUMBER",
      "abbrev": "YORKSHIREANDTHEHUMBER",
      "name": "Yorkshire and the Humber",
      "bounds": [
        53.29,
        -2.55,
        54.56,
        0.15
      ]
    }
  },
  "IE": {
    "CE": {
      "code": "IE-CE",
      "abbrev": "CE",
      "name": "Clare",
      "bounds": [
        52.56,
        -9.94,
        53.17,
        -8.28
      ]
    },
    "CN": {
      "code": "IE-CN",
      "abbrev": "CN",
      "name": "Cavan",
      "bounds": [
        53.77,
        -8.05,
        54.3,
        -6.75
      ]
    },
    "CO": {
      "code": "IE-CO",
      "abbrev": "CO",
      "name": "Cork",
      "bounds": [
        51.45,
        -10.16,
        52.38,
        -7.85
      ]
    },
    "CW": {
      "code": "IE-CW",
      "abbrev": "CW",
      "name": "Carlow",
      "bounds": [
        52.47,
        -7.09,
        52.92,
        -6.5
      ]
    },
    "D": {
      "code": "IE-D",
      "abbrev": "D",
      "name": "Dublin",
      "bounds": [
        53.18,
        -6.53,
        53.63,
        -6.05
      ]
    },
    "DL": {
      "code": "IE-DL",
      "abbrev": "DL",
      "name": "Donegal",
      "bounds": [
        54.46,
        -8.8,
        55.39,
        -6.94
      ]
    },
    "G": {
      "code": "IE-G",
      "abbrev": "G",
      "name": "Galway",
      "bounds": [
        52.97,
        -10.2,
        53.72,
        -7.97
      ]
    },
    "KE": {
      "code": "IE-KE",
      "abbrev": "KE",
      "name": "Kildare",
      "bounds": [
        52.86,
        -7.14,
        53.45,
        -6.46
      ]
    },
    "KK": {
      "code": "IE-KK",
      "abbrev": "KK",
      "name": "Kilkenny",
      "bounds": [
        52.25,
        -7.67,
        52.89,
        -6.92
      ]
    },
    "KY": {
      "code": "IE-KY",
      "abbrev": "KY",
      "name": "Kerry",
      "bounds": [
        51.69,
        -10.48,
        52.58,
        -9.12
      ]
    },
    "LD": {
      "code": "IE-LD",
      "abbrev": "LD",
      "name": "Longford",
      "bounds": [
        53.52,
        -8.03,
        53.94,
        -7.37
      ]
    },
    "LH": {
      "code": "IE-LH",
      "abbrev": "LH",
      "name": "Louth",
      "bounds": [
        53.72,
        -6.68,
        54.11,
        -6.11
      ]
    },
    "LK": {
      "code": "IE-LK",
      "abbrev": "LK",
      "name": "Limerick",
      "bounds": [
        52.28,
        -9.36,
        52.76,
        -8.16
      ]
    },
    "LM": {
      "code": "IE-LM",
      "abbrev": "LM",
      "name": "Leitrim",
      "bounds": [
        53.81,
        -8.41,
        54.48,
        -7.58
      ]
    },
    "LS": {
      "code": "IE-LS",
      "abbrev": "LS",
      "name": "Laoighis",
      "bounds": [
        52.78,
        -7.73,
        53.21,
        -6.93
      ]
    },
    "MH": {
      "code": "IE-MH",
      "abbrev": "MH",
      "name": "Meath",
      "bounds": [
        53.38,
        -7.34,
        53.92,
        -6.2
      ]
    },
    "MN": {
      "code": "IE-MN",
      "abbrev": "MN",
      "name": "Monaghan",
      "bounds": [
        53.91,
        -7.33,
        54.41,
        -6.55
      ]
    },
    "MO": {
      "code": "IE-MO",
      "abbrev": "MO",
      "name": "Mayo",
      "bounds": [
        53.48,
        -10.27,
        54.34,
        -8.58
      ]
    },
    "OY": {
      "code": "IE-OY",
      "abbrev": "OY",
      "name": "Offaly",
      "bounds": [
        52.85,
        -8.08,
        53.43,
        -6.99
      ]
    },
    "RN": {
      "code": "IE-RN",
      "abbrev": "RN",
      "name": "Roscommon",
      "bounds": [
        53.28,
        -8.82,
        54.11,
        -7.88
      ]
    },
    "SO": {
      "code": "IE-SO",
      "abbrev": "SO",
      "name": "Sligo",
      "bounds": [
        53.91,
        -9.13,
        54.48,
        -8.16
      ]
    },
    "TA": {
      "code": "IE-TA",
      "abbrev": "TA",
      "name": "North Tipperary",
      "bounds": [
        52.21,
        -8.48,
        53.17,
        -7.36
      ]
    },
    "WD": {
      "code": "IE-WD",
      "abbrev": "WD",
      "name": "Waterford",
      "bounds": [
        51.94,
        -8.15,
        52.36,
        -6.96
      ]
    },
    "WH": {
      "code": "IE-WH",
      "abbrev": "WH",
      "name": "Westmeath",
      "bounds": [
        53.32,
        -7.96,
        53.8,
        -6.95
      ]
    },
    "WW": {
      "code": "IE-WW",
      "abbrev": "WW",
      "name": "Wicklow",
      "bounds": [
        52.68,
        -6.78,
        53.22,
        -5.99
      ]
    },
    "WX": {
      "code": "IE-WX",
      "abbrev": "WX",
      "name": "Wexford",
      "bounds": [
        52.12,
        -7.02,
        52.79,
        -6.15
      ]
    }
  }
};
