// KV store with write notifications.
//
// Re-exports kv_store.tsx (autogenerated, not edited) and reports which keys each
// write touched, so the static-file publisher can rebuild exactly the public files
// those keys feed — without every write site having to remember to call it.
import * as raw from "./kv_store.tsx";

export type KvWriteKind = "set" | "del";
type Listener = (keys: string[], kind: KvWriteKind) => void;

let listener: Listener | null = null;

/** Register the single write listener (index.ts wires this to the publisher). */
export function onKvWrite(fn: Listener): void {
  listener = fn;
}

function notify(keys: string[], kind: KvWriteKind): void {
  if (!listener || !keys.length) return;
  try {
    listener(keys, kind);
  } catch (e) {
    console.warn("kv write listener failed:", e);
  }
}

export const get = raw.get;
export const mget = raw.mget;
export const getByPrefix = raw.getByPrefix;

export async function set(key: string, value: any): Promise<void> {
  await raw.set(key, value);
  notify([key], "set");
}

export async function mset(keys: string[], values: any[]): Promise<void> {
  await raw.mset(keys, values);
  notify(keys, "set");
}

export async function del(key: string): Promise<void> {
  await raw.del(key);
  notify([key], "del");
}

export async function mdel(keys: string[]): Promise<void> {
  await raw.mdel(keys);
  notify(keys, "del");
}
