// GENERATED by scripts/generate-admin1.mjs — do not edit by hand.
// Non-US regions the ingest can query, keyed by the abbrev used in KV keys and
// URLs. `iso` is a real ISO 3166-2 code that Overpass resolves as an area.
export interface IntlRegion{cc:string;a:string;n:string;iso:string;la:number;lo:number;b:[number,number,number,number];}
export const INTL_REGIONS:Record<string,IntlRegion>={
  "AB": {
    "cc": "CA",
    "a": "AB",
    "n": "Alberta",
    "iso": "CA-AB",
    "la": 54.5,
    "lo": -115,
    "b": [
      48.99,
      -120,
      60,
      -110
    ]
  },
  "BC": {
    "cc": "CA",
    "a": "BC",
    "n": "British Columbia",
    "iso": "CA-BC",
    "la": 54.16,
    "lo": -126.55,
    "b": [
      48.32,
      -139.06,
      60,
      -114.05
    ]
  },
  "MB": {
    "cc": "CA",
    "a": "MB",
    "n": "Manitoba",
    "iso": "CA-MB",
    "la": 54.5,
    "lo": -95.47,
    "b": [
      48.99,
      -102,
      60,
      -88.95
    ]
  },
  "NB": {
    "cc": "CA",
    "a": "NB",
    "n": "New Brunswick",
    "iso": "CA-NB",
    "la": 46.35,
    "lo": -66.44,
    "b": [
      44.63,
      -69.05,
      48.07,
      -63.83
    ]
  },
  "NL": {
    "cc": "CA",
    "a": "NL",
    "n": "Newfoundland and Labrador",
    "iso": "CA-NL",
    "la": 53.47,
    "lo": -60.2,
    "b": [
      46.63,
      -67.76,
      60.31,
      -52.65
    ]
  },
  "NS": {
    "cc": "CA",
    "a": "NS",
    "n": "Nova Scotia",
    "iso": "CA-NS",
    "la": 45.27,
    "lo": -63.02,
    "b": [
      43.52,
      -66.32,
      47.01,
      -59.73
    ]
  },
  "NT": {
    "cc": "CA",
    "a": "NT",
    "n": "Northwest Territories",
    "iso": "CA-NT",
    "la": 69.38,
    "lo": -119.22,
    "b": [
      60,
      -136.45,
      78.76,
      -101.99
    ]
  },
  "NU": {
    "cc": "CA",
    "a": "NU",
    "n": "Nunavut",
    "iso": "CA-NU",
    "la": 67.53,
    "lo": -90.94,
    "b": [
      51.94,
      -120.68,
      83.12,
      -61.21
    ]
  },
  "ON": {
    "cc": "CA",
    "a": "ON",
    "n": "Ontario",
    "iso": "CA-ON",
    "la": 49.26,
    "lo": -84.75,
    "b": [
      41.67,
      -95.16,
      56.85,
      -74.34
    ]
  },
  "PE": {
    "cc": "CA",
    "a": "PE",
    "n": "Prince Edward Island",
    "iso": "CA-PE",
    "la": 46.52,
    "lo": -63.21,
    "b": [
      45.97,
      -64.4,
      47.06,
      -62.02
    ]
  },
  "QC": {
    "cc": "CA",
    "a": "QC",
    "n": "Québec",
    "iso": "CA-QC",
    "la": 53.79,
    "lo": -68.4,
    "b": [
      45,
      -79.71,
      62.57,
      -57.1
    ]
  },
  "SK": {
    "cc": "CA",
    "a": "SK",
    "n": "Saskatchewan",
    "iso": "CA-SK",
    "la": 54.5,
    "lo": -105.68,
    "b": [
      48.99,
      -110,
      60,
      -101.37
    ]
  },
  "YT": {
    "cc": "CA",
    "a": "YT",
    "n": "Yukon",
    "iso": "CA-YT",
    "la": 64.83,
    "lo": -132.41,
    "b": [
      60,
      -141,
      69.65,
      -123.82
    ]
  }
};
