// GENERATED by scripts/generate-admin1.mjs — do not edit by hand.
// Non-US regions the ingest can query, keyed by the abbrev used in KV keys and
// URLs. `iso` is a real ISO 3166-2 code that Overpass resolves as an area.
// GB English ITL1 regions share iso GB-ENG and are clipped by bounds in parse().
export interface IntlRegion{cc:string;a:string;n:string;iso:string;la:number;lo:number;b:[number,number,number,number];}
export const INTL_REGIONS:Record<string,IntlRegion>={
  "AB": {
    "cc": "CA",
    "a": "AB",
    "n": "Alberta",
    "iso": "CA-AB",
    "la": 54.5,
    "lo": -115,
    "b": [
      48.99,
      -120,
      60,
      -110
    ]
  },
  "BC": {
    "cc": "CA",
    "a": "BC",
    "n": "British Columbia",
    "iso": "CA-BC",
    "la": 54.16,
    "lo": -126.55,
    "b": [
      48.32,
      -139.06,
      60,
      -114.05
    ]
  },
  "MB": {
    "cc": "CA",
    "a": "MB",
    "n": "Manitoba",
    "iso": "CA-MB",
    "la": 54.5,
    "lo": -95.47,
    "b": [
      48.99,
      -102,
      60,
      -88.95
    ]
  },
  "NB": {
    "cc": "CA",
    "a": "NB",
    "n": "New Brunswick",
    "iso": "CA-NB",
    "la": 46.35,
    "lo": -66.44,
    "b": [
      44.63,
      -69.05,
      48.07,
      -63.83
    ]
  },
  "NL": {
    "cc": "CA",
    "a": "NL",
    "n": "Newfoundland and Labrador",
    "iso": "CA-NL",
    "la": 53.47,
    "lo": -60.2,
    "b": [
      46.63,
      -67.76,
      60.31,
      -52.65
    ]
  },
  "NS": {
    "cc": "CA",
    "a": "NS",
    "n": "Nova Scotia",
    "iso": "CA-NS",
    "la": 45.27,
    "lo": -63.02,
    "b": [
      43.52,
      -66.32,
      47.01,
      -59.73
    ]
  },
  "NT": {
    "cc": "CA",
    "a": "NT",
    "n": "Northwest Territories",
    "iso": "CA-NT",
    "la": 69.38,
    "lo": -119.22,
    "b": [
      60,
      -136.45,
      78.76,
      -101.99
    ]
  },
  "NU": {
    "cc": "CA",
    "a": "NU",
    "n": "Nunavut",
    "iso": "CA-NU",
    "la": 67.53,
    "lo": -90.94,
    "b": [
      51.94,
      -120.68,
      83.12,
      -61.21
    ]
  },
  "ON": {
    "cc": "CA",
    "a": "ON",
    "n": "Ontario",
    "iso": "CA-ON",
    "la": 49.26,
    "lo": -84.75,
    "b": [
      41.67,
      -95.16,
      56.85,
      -74.34
    ]
  },
  "PE": {
    "cc": "CA",
    "a": "PE",
    "n": "Prince Edward Island",
    "iso": "CA-PE",
    "la": 46.52,
    "lo": -63.21,
    "b": [
      45.97,
      -64.4,
      47.06,
      -62.02
    ]
  },
  "QC": {
    "cc": "CA",
    "a": "QC",
    "n": "Québec",
    "iso": "CA-QC",
    "la": 53.79,
    "lo": -68.4,
    "b": [
      45,
      -79.71,
      62.57,
      -57.1
    ]
  },
  "SK": {
    "cc": "CA",
    "a": "SK",
    "n": "Saskatchewan",
    "iso": "CA-SK",
    "la": 54.5,
    "lo": -105.68,
    "b": [
      48.99,
      -110,
      60,
      -101.37
    ]
  },
  "YT": {
    "cc": "CA",
    "a": "YT",
    "n": "Yukon",
    "iso": "CA-YT",
    "la": 64.83,
    "lo": -132.41,
    "b": [
      60,
      -141,
      69.65,
      -123.82
    ]
  },
  "EAST": {
    "cc": "GB",
    "a": "EAST",
    "n": "East",
    "iso": "GB-ENG",
    "la": 52.22,
    "lo": 0.52,
    "b": [
      51.45,
      -0.73,
      52.99,
      1.77
    ]
  },
  "EASTMIDLANDS": {
    "cc": "GB",
    "a": "EASTMIDLANDS",
    "n": "East Midlands",
    "iso": "GB-ENG",
    "la": 52.8,
    "lo": -0.83,
    "b": [
      51.98,
      -2.02,
      53.61,
      0.36
    ]
  },
  "GREATERLONDON": {
    "cc": "GB",
    "a": "GREATERLONDON",
    "n": "Greater London",
    "iso": "GB-ENG",
    "la": 51.49,
    "lo": -0.08,
    "b": [
      51.28,
      -0.5,
      51.69,
      0.34
    ]
  },
  "NORTHEAST": {
    "cc": "GB",
    "a": "NORTHEAST",
    "n": "North East",
    "iso": "GB-ENG",
    "la": 55.13,
    "lo": -1.73,
    "b": [
      54.44,
      -2.68,
      55.81,
      -0.78
    ]
  },
  "NORTHWEST": {
    "cc": "GB",
    "a": "NORTHWEST",
    "n": "North West",
    "iso": "GB-ENG",
    "la": 54.07,
    "lo": -2.76,
    "b": [
      52.95,
      -3.63,
      55.19,
      -1.9
    ]
  },
  "NORTHERNIRELAND": {
    "cc": "GB",
    "a": "NORTHERNIRELAND",
    "n": "Northern Ireland",
    "iso": "GB-NIR",
    "la": 54.67,
    "lo": -6.8,
    "b": [
      54.03,
      -8.17,
      55.31,
      -5.43
    ]
  },
  "SCOTLAND": {
    "cc": "GB",
    "a": "SCOTLAND",
    "n": "Scotland",
    "iso": "GB-SCT",
    "la": 57.74,
    "lo": -7.22,
    "b": [
      54.63,
      -13.69,
      60.85,
      -0.75
    ]
  },
  "SOUTHEAST": {
    "cc": "GB",
    "a": "SOUTHEAST",
    "n": "South East",
    "iso": "GB-ENG",
    "la": 51.39,
    "lo": -0.25,
    "b": [
      50.58,
      -1.95,
      52.19,
      1.45
    ]
  },
  "SOUTHWEST": {
    "cc": "GB",
    "a": "SOUTHWEST",
    "n": "South West",
    "iso": "GB-ENG",
    "la": 51.01,
    "lo": -3.92,
    "b": [
      49.91,
      -6.35,
      52.11,
      -1.49
    ]
  },
  "WALES": {
    "cc": "GB",
    "a": "WALES",
    "n": "Wales",
    "iso": "GB-WLS",
    "la": 52.41,
    "lo": -3.98,
    "b": [
      51.38,
      -5.31,
      53.43,
      -2.65
    ]
  },
  "WESTMIDLANDS": {
    "cc": "GB",
    "a": "WESTMIDLANDS",
    "n": "West Midlands",
    "iso": "GB-ENG",
    "la": 52.52,
    "lo": -2.2,
    "b": [
      51.82,
      -3.22,
      53.21,
      -1.17
    ]
  },
  "YORKSHIREANDTHEHUMBER": {
    "cc": "GB",
    "a": "YORKSHIREANDTHEHUMBER",
    "n": "Yorkshire and the Humber",
    "iso": "GB-ENG",
    "la": 53.93,
    "lo": -1.2,
    "b": [
      53.29,
      -2.55,
      54.56,
      0.15
    ]
  },
  "IECE": {
    "cc": "IE",
    "a": "IECE",
    "n": "Clare",
    "iso": "IE-CE",
    "la": 52.87,
    "lo": -9.11,
    "b": [
      52.56,
      -9.94,
      53.17,
      -8.28
    ]
  },
  "IECN": {
    "cc": "IE",
    "a": "IECN",
    "n": "Cavan",
    "iso": "IE-CN",
    "la": 54.04,
    "lo": -7.4,
    "b": [
      53.77,
      -8.05,
      54.3,
      -6.75
    ]
  },
  "IECO": {
    "cc": "IE",
    "a": "IECO",
    "n": "Cork",
    "iso": "IE-CO",
    "la": 51.92,
    "lo": -9,
    "b": [
      51.45,
      -10.16,
      52.38,
      -7.85
    ]
  },
  "IECW": {
    "cc": "IE",
    "a": "IECW",
    "n": "Carlow",
    "iso": "IE-CW",
    "la": 52.7,
    "lo": -6.79,
    "b": [
      52.47,
      -7.09,
      52.92,
      -6.5
    ]
  },
  "IED": {
    "cc": "IE",
    "a": "IED",
    "n": "Dublin",
    "iso": "IE-D",
    "la": 53.41,
    "lo": -6.29,
    "b": [
      53.18,
      -6.53,
      53.63,
      -6.05
    ]
  },
  "IEDL": {
    "cc": "IE",
    "a": "IEDL",
    "n": "Donegal",
    "iso": "IE-DL",
    "la": 54.93,
    "lo": -7.87,
    "b": [
      54.46,
      -8.8,
      55.39,
      -6.94
    ]
  },
  "IEG": {
    "cc": "IE",
    "a": "IEG",
    "n": "Galway",
    "iso": "IE-G",
    "la": 53.35,
    "lo": -9.08,
    "b": [
      52.97,
      -10.2,
      53.72,
      -7.97
    ]
  },
  "IEKE": {
    "cc": "IE",
    "a": "IEKE",
    "n": "Kildare",
    "iso": "IE-KE",
    "la": 53.16,
    "lo": -6.8,
    "b": [
      52.86,
      -7.14,
      53.45,
      -6.46
    ]
  },
  "IEKK": {
    "cc": "IE",
    "a": "IEKK",
    "n": "Kilkenny",
    "iso": "IE-KK",
    "la": 52.57,
    "lo": -7.29,
    "b": [
      52.25,
      -7.67,
      52.89,
      -6.92
    ]
  },
  "IEKY": {
    "cc": "IE",
    "a": "IEKY",
    "n": "Kerry",
    "iso": "IE-KY",
    "la": 52.14,
    "lo": -9.8,
    "b": [
      51.69,
      -10.48,
      52.58,
      -9.12
    ]
  },
  "IELD": {
    "cc": "IE",
    "a": "IELD",
    "n": "Longford",
    "iso": "IE-LD",
    "la": 53.73,
    "lo": -7.7,
    "b": [
      53.52,
      -8.03,
      53.94,
      -7.37
    ]
  },
  "IELH": {
    "cc": "IE",
    "a": "IELH",
    "n": "Louth",
    "iso": "IE-LH",
    "la": 53.92,
    "lo": -6.39,
    "b": [
      53.72,
      -6.68,
      54.11,
      -6.11
    ]
  },
  "IELK": {
    "cc": "IE",
    "a": "IELK",
    "n": "Limerick",
    "iso": "IE-LK",
    "la": 52.52,
    "lo": -8.76,
    "b": [
      52.28,
      -9.36,
      52.76,
      -8.16
    ]
  },
  "IELM": {
    "cc": "IE",
    "a": "IELM",
    "n": "Leitrim",
    "iso": "IE-LM",
    "la": 54.15,
    "lo": -7.99,
    "b": [
      53.81,
      -8.41,
      54.48,
      -7.58
    ]
  },
  "IELS": {
    "cc": "IE",
    "a": "IELS",
    "n": "Laoighis",
    "iso": "IE-LS",
    "la": 53,
    "lo": -7.33,
    "b": [
      52.78,
      -7.73,
      53.21,
      -6.93
    ]
  },
  "IEMH": {
    "cc": "IE",
    "a": "IEMH",
    "n": "Meath",
    "iso": "IE-MH",
    "la": 53.65,
    "lo": -6.77,
    "b": [
      53.38,
      -7.34,
      53.92,
      -6.2
    ]
  },
  "IEMN": {
    "cc": "IE",
    "a": "IEMN",
    "n": "Monaghan",
    "iso": "IE-MN",
    "la": 54.16,
    "lo": -6.94,
    "b": [
      53.91,
      -7.33,
      54.41,
      -6.55
    ]
  },
  "IEMO": {
    "cc": "IE",
    "a": "IEMO",
    "n": "Mayo",
    "iso": "IE-MO",
    "la": 53.91,
    "lo": -9.43,
    "b": [
      53.48,
      -10.27,
      54.34,
      -8.58
    ]
  },
  "IEOY": {
    "cc": "IE",
    "a": "IEOY",
    "n": "Offaly",
    "iso": "IE-OY",
    "la": 53.14,
    "lo": -7.53,
    "b": [
      52.85,
      -8.08,
      53.43,
      -6.99
    ]
  },
  "IERN": {
    "cc": "IE",
    "a": "IERN",
    "n": "Roscommon",
    "iso": "IE-RN",
    "la": 53.7,
    "lo": -8.35,
    "b": [
      53.28,
      -8.82,
      54.11,
      -7.88
    ]
  },
  "IESO": {
    "cc": "IE",
    "a": "IESO",
    "n": "Sligo",
    "iso": "IE-SO",
    "la": 54.19,
    "lo": -8.64,
    "b": [
      53.91,
      -9.13,
      54.48,
      -8.16
    ]
  },
  "IETA": {
    "cc": "IE",
    "a": "IETA",
    "n": "North Tipperary",
    "iso": "IE-TA",
    "la": 52.69,
    "lo": -7.92,
    "b": [
      52.21,
      -8.48,
      53.17,
      -7.36
    ]
  },
  "IEWD": {
    "cc": "IE",
    "a": "IEWD",
    "n": "Waterford",
    "iso": "IE-WD",
    "la": 52.15,
    "lo": -7.55,
    "b": [
      51.94,
      -8.15,
      52.36,
      -6.96
    ]
  },
  "IEWH": {
    "cc": "IE",
    "a": "IEWH",
    "n": "Westmeath",
    "iso": "IE-WH",
    "la": 53.56,
    "lo": -7.45,
    "b": [
      53.32,
      -7.96,
      53.8,
      -6.95
    ]
  },
  "IEWW": {
    "cc": "IE",
    "a": "IEWW",
    "n": "Wicklow",
    "iso": "IE-WW",
    "la": 52.95,
    "lo": -6.38,
    "b": [
      52.68,
      -6.78,
      53.22,
      -5.99
    ]
  },
  "IEWX": {
    "cc": "IE",
    "a": "IEWX",
    "n": "Wexford",
    "iso": "IE-WX",
    "la": 52.46,
    "lo": -6.58,
    "b": [
      52.12,
      -7.02,
      52.79,
      -6.15
    ]
  },
  "FR01": {
    "cc": "FR",
    "a": "FR01",
    "n": "Ain",
    "iso": "FR-01",
    "la": 46.08,
    "lo": 5.45,
    "b": [
      45.64,
      4.75,
      46.51,
      6.14
    ]
  },
  "FR02": {
    "cc": "FR",
    "a": "FR02",
    "n": "Aisne",
    "iso": "FR-02",
    "la": 49.46,
    "lo": 3.61,
    "b": [
      48.85,
      2.96,
      50.06,
      4.25
    ]
  },
  "FR03": {
    "cc": "FR",
    "a": "FR03",
    "n": "Allier",
    "iso": "FR-03",
    "la": 46.38,
    "lo": 3.13,
    "b": [
      45.96,
      2.25,
      46.79,
      4
    ]
  },
  "FR04": {
    "cc": "FR",
    "a": "FR04",
    "n": "Alpes-de-Haute-Provence",
    "iso": "FR-04",
    "la": 44.17,
    "lo": 6.23,
    "b": [
      43.67,
      5.5,
      44.66,
      6.95
    ]
  },
  "FR05": {
    "cc": "FR",
    "a": "FR05",
    "n": "Hautes-Alpes",
    "iso": "FR-05",
    "la": 44.66,
    "lo": 6.24,
    "b": [
      44.19,
      5.43,
      45.12,
      7.06
    ]
  },
  "FR06": {
    "cc": "FR",
    "a": "FR06",
    "n": "Alpes-Maritimes",
    "iso": "FR-06",
    "la": 43.92,
    "lo": 7.17,
    "b": [
      43.48,
      6.64,
      44.35,
      7.69
    ]
  },
  "FR07": {
    "cc": "FR",
    "a": "FR07",
    "n": "Ardèche",
    "iso": "FR-07",
    "la": 44.83,
    "lo": 4.38,
    "b": [
      44.28,
      3.87,
      45.37,
      4.89
    ]
  },
  "FR08": {
    "cc": "FR",
    "a": "FR08",
    "n": "Ardennes",
    "iso": "FR-08",
    "la": 49.7,
    "lo": 4.71,
    "b": [
      49.24,
      4.03,
      50.16,
      5.39
    ]
  },
  "FR09": {
    "cc": "FR",
    "a": "FR09",
    "n": "Ariège",
    "iso": "FR-09",
    "la": 42.94,
    "lo": 1.5,
    "b": [
      42.57,
      0.83,
      43.31,
      2.17
    ]
  },
  "FR10": {
    "cc": "FR",
    "a": "FR10",
    "n": "Aube",
    "iso": "FR-10",
    "la": 48.32,
    "lo": 4.13,
    "b": [
      47.92,
      3.39,
      48.71,
      4.86
    ]
  },
  "FR11": {
    "cc": "FR",
    "a": "FR11",
    "n": "Aude",
    "iso": "FR-11",
    "la": 43.05,
    "lo": 2.47,
    "b": [
      42.65,
      1.7,
      43.44,
      3.24
    ]
  },
  "FR12": {
    "cc": "FR",
    "a": "FR12",
    "n": "Aveyron",
    "iso": "FR-12",
    "la": 44.32,
    "lo": 2.64,
    "b": [
      43.69,
      1.83,
      44.94,
      3.45
    ]
  },
  "FR13": {
    "cc": "FR",
    "a": "FR13",
    "n": "Bouches-du-Rhône",
    "iso": "FR-13",
    "la": 43.55,
    "lo": 5.01,
    "b": [
      43.16,
      4.21,
      43.93,
      5.81
    ]
  },
  "FR14": {
    "cc": "FR",
    "a": "FR14",
    "n": "Calvados",
    "iso": "FR-14",
    "la": 49.09,
    "lo": -0.36,
    "b": [
      48.75,
      -1.15,
      49.43,
      0.43
    ]
  },
  "FR15": {
    "cc": "FR",
    "a": "FR15",
    "n": "Cantal",
    "iso": "FR-15",
    "la": 45.05,
    "lo": 2.72,
    "b": [
      44.62,
      2.06,
      45.48,
      3.37
    ]
  },
  "FR16": {
    "cc": "FR",
    "a": "FR16",
    "n": "Charente",
    "iso": "FR-16",
    "la": 45.67,
    "lo": 0.23,
    "b": [
      45.19,
      -0.46,
      46.14,
      0.92
    ]
  },
  "FR17": {
    "cc": "FR",
    "a": "FR17",
    "n": "Charente-Maritime",
    "iso": "FR-17",
    "la": 45.73,
    "lo": -0.78,
    "b": [
      45.1,
      -1.56,
      46.36,
      0
    ]
  },
  "FR18": {
    "cc": "FR",
    "a": "FR18",
    "n": "Cher",
    "iso": "FR-18",
    "la": 47.02,
    "lo": 2.42,
    "b": [
      46.42,
      1.77,
      47.62,
      3.08
    ]
  },
  "FR19": {
    "cc": "FR",
    "a": "FR19",
    "n": "Corrèze",
    "iso": "FR-19",
    "la": 45.35,
    "lo": 1.88,
    "b": [
      44.93,
      1.24,
      45.76,
      2.53
    ]
  },
  "FR21": {
    "cc": "FR",
    "a": "FR21",
    "n": "Côte-d'Or",
    "iso": "FR-21",
    "la": 47.46,
    "lo": 4.79,
    "b": [
      46.9,
      4.06,
      48.02,
      5.52
    ]
  },
  "FR22": {
    "cc": "FR",
    "a": "FR22",
    "n": "Côtes-d'Armor",
    "iso": "FR-22",
    "la": 48.46,
    "lo": -2.77,
    "b": [
      48.03,
      -3.64,
      48.88,
      -1.91
    ]
  },
  "FR23": {
    "cc": "FR",
    "a": "FR23",
    "n": "Creuse",
    "iso": "FR-23",
    "la": 46.06,
    "lo": 2,
    "b": [
      45.67,
      1.39,
      46.45,
      2.6
    ]
  },
  "FR24": {
    "cc": "FR",
    "a": "FR24",
    "n": "Dordogne",
    "iso": "FR-24",
    "la": 45.14,
    "lo": 0.72,
    "b": [
      44.57,
      -0.03,
      45.71,
      1.46
    ]
  },
  "FR25": {
    "cc": "FR",
    "a": "FR25",
    "n": "Doubs",
    "iso": "FR-25",
    "la": 47.06,
    "lo": 6.37,
    "b": [
      46.56,
      5.7,
      47.56,
      7.04
    ]
  },
  "FR26": {
    "cc": "FR",
    "a": "FR26",
    "n": "Drôme",
    "iso": "FR-26",
    "la": 44.73,
    "lo": 5.25,
    "b": [
      44.12,
      4.66,
      45.34,
      5.83
    ]
  },
  "FR27": {
    "cc": "FR",
    "a": "FR27",
    "n": "Eure",
    "iso": "FR-27",
    "la": 49.08,
    "lo": 1.03,
    "b": [
      48.67,
      0.29,
      49.49,
      1.78
    ]
  },
  "FR28": {
    "cc": "FR",
    "a": "FR28",
    "n": "Eure-et-Loir",
    "iso": "FR-28",
    "la": 48.45,
    "lo": 1.39,
    "b": [
      47.95,
      0.78,
      48.94,
      2
    ]
  },
  "FR29": {
    "cc": "FR",
    "a": "FR29",
    "n": "Finistère",
    "iso": "FR-29",
    "la": 48.25,
    "lo": -4.26,
    "b": [
      47.77,
      -5.13,
      48.73,
      -3.39
    ]
  },
  "FR2A": {
    "cc": "FR",
    "a": "FR2A",
    "n": "Corse-du-Sud",
    "iso": "FR-2A",
    "la": 41.88,
    "lo": 8.98,
    "b": [
      41.37,
      8.55,
      42.39,
      9.4
    ]
  },
  "FR2B": {
    "cc": "FR",
    "a": "FR2B",
    "n": "Haute-Corse",
    "iso": "FR-2B",
    "la": 42.43,
    "lo": 9.07,
    "b": [
      41.83,
      8.57,
      43.02,
      9.56
    ]
  },
  "FR30": {
    "cc": "FR",
    "a": "FR30",
    "n": "Gard",
    "iso": "FR-30",
    "la": 43.96,
    "lo": 4.07,
    "b": [
      43.46,
      3.29,
      44.46,
      4.85
    ]
  },
  "FR31": {
    "cc": "FR",
    "a": "FR31",
    "n": "Haute-Garonne",
    "iso": "FR-31",
    "la": 43.3,
    "lo": 1.24,
    "b": [
      42.68,
      0.44,
      43.92,
      2.05
    ]
  },
  "FR32": {
    "cc": "FR",
    "a": "FR32",
    "n": "Gers",
    "iso": "FR-32",
    "la": 43.69,
    "lo": 0.46,
    "b": [
      43.31,
      -0.27,
      44.07,
      1.19
    ]
  },
  "FR33": {
    "cc": "FR",
    "a": "FR33",
    "n": "Gironde",
    "iso": "FR-33",
    "la": 44.89,
    "lo": -0.47,
    "b": [
      44.2,
      -1.26,
      45.57,
      0.32
    ]
  },
  "FR34": {
    "cc": "FR",
    "a": "FR34",
    "n": "Hérault",
    "iso": "FR-34",
    "la": 43.6,
    "lo": 3.37,
    "b": [
      43.22,
      2.56,
      43.97,
      4.18
    ]
  },
  "FR35": {
    "cc": "FR",
    "a": "FR35",
    "n": "Ille-et-Vilaine",
    "iso": "FR-35",
    "la": 48.17,
    "lo": -1.66,
    "b": [
      47.63,
      -2.29,
      48.71,
      -1.04
    ]
  },
  "FR36": {
    "cc": "FR",
    "a": "FR36",
    "n": "Indre",
    "iso": "FR-36",
    "la": 46.82,
    "lo": 1.54,
    "b": [
      46.35,
      0.88,
      47.29,
      2.19
    ]
  },
  "FR37": {
    "cc": "FR",
    "a": "FR37",
    "n": "Indre-et-Loire",
    "iso": "FR-37",
    "la": 47.23,
    "lo": 0.72,
    "b": [
      46.74,
      0.07,
      47.71,
      1.36
    ]
  },
  "FR38": {
    "cc": "FR",
    "a": "FR38",
    "n": "Isère",
    "iso": "FR-38",
    "la": 45.3,
    "lo": 5.57,
    "b": [
      44.71,
      4.76,
      45.88,
      6.37
    ]
  },
  "FR39": {
    "cc": "FR",
    "a": "FR39",
    "n": "Jura",
    "iso": "FR-39",
    "la": 46.78,
    "lo": 5.73,
    "b": [
      46.26,
      5.25,
      47.29,
      6.21
    ]
  },
  "FR40": {
    "cc": "FR",
    "a": "FR40",
    "n": "Landes",
    "iso": "FR-40",
    "la": 44.01,
    "lo": -0.68,
    "b": [
      43.49,
      -1.51,
      44.53,
      0.14
    ]
  },
  "FR41": {
    "cc": "FR",
    "a": "FR41",
    "n": "Loir-et-Cher",
    "iso": "FR-41",
    "la": 47.66,
    "lo": 1.43,
    "b": [
      47.19,
      0.6,
      48.13,
      2.26
    ]
  },
  "FR42": {
    "cc": "FR",
    "a": "FR42",
    "n": "Loire",
    "iso": "FR-42",
    "la": 45.76,
    "lo": 4.22,
    "b": [
      45.24,
      3.67,
      46.28,
      4.77
    ]
  },
  "FR43": {
    "cc": "FR",
    "a": "FR43",
    "n": "Haute-Loire",
    "iso": "FR-43",
    "la": 45.09,
    "lo": 3.79,
    "b": [
      44.75,
      3.1,
      45.42,
      4.48
    ]
  },
  "FR44": {
    "cc": "FR",
    "a": "FR44",
    "n": "Loire-Atlantique",
    "iso": "FR-44",
    "la": 47.35,
    "lo": -1.74,
    "b": [
      46.86,
      -2.56,
      47.83,
      -0.92
    ]
  },
  "FR45": {
    "cc": "FR",
    "a": "FR45",
    "n": "Loiret",
    "iso": "FR-45",
    "la": 47.92,
    "lo": 2.32,
    "b": [
      47.49,
      1.52,
      48.34,
      3.12
    ]
  },
  "FR46": {
    "cc": "FR",
    "a": "FR46",
    "n": "Lot",
    "iso": "FR-46",
    "la": 44.64,
    "lo": 1.61,
    "b": [
      44.22,
      1,
      45.05,
      2.21
    ]
  },
  "FR47": {
    "cc": "FR",
    "a": "FR47",
    "n": "Lot-et-Garonne",
    "iso": "FR-47",
    "la": 44.36,
    "lo": 0.47,
    "b": [
      43.97,
      -0.14,
      44.76,
      1.08
    ]
  },
  "FR48": {
    "cc": "FR",
    "a": "FR48",
    "n": "Lozère",
    "iso": "FR-48",
    "la": 44.54,
    "lo": 3.49,
    "b": [
      44.11,
      2.98,
      44.96,
      3.99
    ]
  },
  "FR49": {
    "cc": "FR",
    "a": "FR49",
    "n": "Maine-et-Loire",
    "iso": "FR-49",
    "la": 47.4,
    "lo": -0.55,
    "b": [
      46.99,
      -1.34,
      47.81,
      0.24
    ]
  },
  "FR50": {
    "cc": "FR",
    "a": "FR50",
    "n": "Manche",
    "iso": "FR-50",
    "la": 49.1,
    "lo": -1.34,
    "b": [
      48.46,
      -1.95,
      49.73,
      -0.74
    ]
  },
  "FR51": {
    "cc": "FR",
    "a": "FR51",
    "n": "Marne",
    "iso": "FR-51",
    "la": 48.97,
    "lo": 4.21,
    "b": [
      48.53,
      3.39,
      49.41,
      5.03
    ]
  },
  "FR52": {
    "cc": "FR",
    "a": "FR52",
    "n": "Haute-Marne",
    "iso": "FR-52",
    "la": 48.14,
    "lo": 5.27,
    "b": [
      47.59,
      4.64,
      48.69,
      5.9
    ]
  },
  "FR53": {
    "cc": "FR",
    "a": "FR53",
    "n": "Mayenne",
    "iso": "FR-53",
    "la": 48.15,
    "lo": -0.64,
    "b": [
      47.74,
      -1.24,
      48.56,
      -0.05
    ]
  },
  "FR54": {
    "cc": "FR",
    "a": "FR54",
    "n": "Meurthe-et-Moselle",
    "iso": "FR-54",
    "la": 48.96,
    "lo": 6.28,
    "b": [
      48.36,
      5.46,
      49.55,
      7.09
    ]
  },
  "FR55": {
    "cc": "FR",
    "a": "FR55",
    "n": "Meuse",
    "iso": "FR-55",
    "la": 49.01,
    "lo": 5.38,
    "b": [
      48.41,
      4.91,
      49.61,
      5.85
    ]
  },
  "FR56": {
    "cc": "FR",
    "a": "FR56",
    "n": "Morbihan",
    "iso": "FR-56",
    "la": 47.76,
    "lo": -2.89,
    "b": [
      47.3,
      -3.73,
      48.21,
      -2.05
    ]
  },
  "FR57": {
    "cc": "FR",
    "a": "FR57",
    "n": "Moselle",
    "iso": "FR-57",
    "la": 49.01,
    "lo": 6.78,
    "b": [
      48.52,
      5.92,
      49.5,
      7.64
    ]
  },
  "FR58": {
    "cc": "FR",
    "a": "FR58",
    "n": "Nièvre",
    "iso": "FR-58",
    "la": 47.11,
    "lo": 3.54,
    "b": [
      46.65,
      2.86,
      47.58,
      4.22
    ]
  },
  "FR59": {
    "cc": "FR",
    "a": "FR59",
    "n": "Nord",
    "iso": "FR-59",
    "la": 50.53,
    "lo": 3.14,
    "b": [
      49.97,
      2.06,
      51.09,
      4.21
    ]
  },
  "FR60": {
    "cc": "FR",
    "a": "FR60",
    "n": "Oise",
    "iso": "FR-60",
    "la": 49.42,
    "lo": 2.42,
    "b": [
      49.07,
      1.68,
      49.77,
      3.17
    ]
  },
  "FR61": {
    "cc": "FR",
    "a": "FR61",
    "n": "Orne",
    "iso": "FR-61",
    "la": 48.58,
    "lo": 0.06,
    "b": [
      48.18,
      -0.86,
      48.97,
      0.98
    ]
  },
  "FR62": {
    "cc": "FR",
    "a": "FR62",
    "n": "Pas-de-Calais",
    "iso": "FR-62",
    "la": 50.52,
    "lo": 2.37,
    "b": [
      50.02,
      1.56,
      51.01,
      3.17
    ]
  },
  "FR63": {
    "cc": "FR",
    "a": "FR63",
    "n": "Puy-de-Dôme",
    "iso": "FR-63",
    "la": 45.78,
    "lo": 3.19,
    "b": [
      45.29,
      2.4,
      46.26,
      3.97
    ]
  },
  "FR64": {
    "cc": "FR",
    "a": "FR64",
    "n": "Pyrénées-Atlantiques",
    "iso": "FR-64",
    "la": 43.18,
    "lo": -0.89,
    "b": [
      42.77,
      -1.8,
      43.59,
      0.02
    ]
  },
  "FR65": {
    "cc": "FR",
    "a": "FR65",
    "n": "Hautes-Pyrénées",
    "iso": "FR-65",
    "la": 43.14,
    "lo": 0.16,
    "b": [
      42.67,
      -0.32,
      43.61,
      0.64
    ]
  },
  "FR66": {
    "cc": "FR",
    "a": "FR66",
    "n": "Pyrénées-Orientales",
    "iso": "FR-66",
    "la": 42.62,
    "lo": 2.45,
    "b": [
      42.33,
      1.71,
      42.91,
      3.18
    ]
  },
  "FR67": {
    "cc": "FR",
    "a": "FR67",
    "n": "Bas-Rhin",
    "iso": "FR-67",
    "la": 48.6,
    "lo": 7.59,
    "b": [
      48.12,
      6.98,
      49.07,
      8.2
    ]
  },
  "FR68": {
    "cc": "FR",
    "a": "FR68",
    "n": "Haute-Rhin",
    "iso": "FR-68",
    "la": 47.86,
    "lo": 7.25,
    "b": [
      47.42,
      6.87,
      48.3,
      7.62
    ]
  },
  "FR69": {
    "cc": "FR",
    "a": "FR69",
    "n": "Rhône",
    "iso": "FR-69M",
    "la": 45.87,
    "lo": 4.71,
    "b": [
      45.44,
      4.25,
      46.3,
      5.16
    ]
  },
  "FR70": {
    "cc": "FR",
    "a": "FR70",
    "n": "Haute-Saône",
    "iso": "FR-70",
    "la": 47.64,
    "lo": 6.11,
    "b": [
      47.26,
      5.37,
      48.01,
      6.84
    ]
  },
  "FR71": {
    "cc": "FR",
    "a": "FR71",
    "n": "Saône-et-Loire",
    "iso": "FR-71",
    "la": 46.67,
    "lo": 4.54,
    "b": [
      46.17,
      3.62,
      47.16,
      5.46
    ]
  },
  "FR72": {
    "cc": "FR",
    "a": "FR72",
    "n": "Sarthe",
    "iso": "FR-72",
    "la": 48.03,
    "lo": 0.24,
    "b": [
      47.58,
      -0.44,
      48.47,
      0.91
    ]
  },
  "FR73": {
    "cc": "FR",
    "a": "FR73",
    "n": "Savoie",
    "iso": "FR-73",
    "la": 45.5,
    "lo": 6.38,
    "b": [
      45.05,
      5.6,
      45.94,
      7.16
    ]
  },
  "FR74": {
    "cc": "FR",
    "a": "FR74",
    "n": "Haute-Savoie",
    "iso": "FR-74",
    "la": 46.07,
    "lo": 6.42,
    "b": [
      45.68,
      5.82,
      46.46,
      7.02
    ]
  },
  "FR75": {
    "cc": "FR",
    "a": "FR75",
    "n": "Paris",
    "iso": "FR-75C",
    "la": 48.86,
    "lo": 2.35,
    "b": [
      48.82,
      2.23,
      48.9,
      2.47
    ]
  },
  "FR76": {
    "cc": "FR",
    "a": "FR76",
    "n": "Seine-Maritime",
    "iso": "FR-76",
    "la": 49.67,
    "lo": 0.93,
    "b": [
      49.26,
      0.08,
      50.07,
      1.77
    ]
  },
  "FR77": {
    "cc": "FR",
    "a": "FR77",
    "n": "Seien-et-Marne",
    "iso": "FR-77",
    "la": 48.61,
    "lo": 2.97,
    "b": [
      48.12,
      2.39,
      49.11,
      3.54
    ]
  },
  "FR78": {
    "cc": "FR",
    "a": "FR78",
    "n": "Yvelines",
    "iso": "FR-78",
    "la": 48.76,
    "lo": 1.84,
    "b": [
      48.44,
      1.44,
      49.08,
      2.23
    ]
  },
  "FR79": {
    "cc": "FR",
    "a": "FR79",
    "n": "Deux-Sèvres",
    "iso": "FR-79",
    "la": 46.54,
    "lo": -0.37,
    "b": [
      45.97,
      -0.95,
      47.1,
      0.2
    ]
  },
  "FR80": {
    "cc": "FR",
    "a": "FR80",
    "n": "Somme",
    "iso": "FR-80",
    "la": 49.98,
    "lo": 2.28,
    "b": [
      49.58,
      1.37,
      50.38,
      3.19
    ]
  },
  "FR81": {
    "cc": "FR",
    "a": "FR81",
    "n": "Tarn",
    "iso": "FR-81",
    "la": 43.79,
    "lo": 2.24,
    "b": [
      43.38,
      1.55,
      44.19,
      2.93
    ]
  },
  "FR82": {
    "cc": "FR",
    "a": "FR82",
    "n": "Tarn-et-Garonne",
    "iso": "FR-82",
    "la": 44.08,
    "lo": 1.36,
    "b": [
      43.77,
      0.74,
      44.39,
      1.98
    ]
  },
  "FR83": {
    "cc": "FR",
    "a": "FR83",
    "n": "Var",
    "iso": "FR-83",
    "la": 43.4,
    "lo": 6.3,
    "b": [
      42.99,
      5.67,
      43.81,
      6.93
    ]
  },
  "FR84": {
    "cc": "FR",
    "a": "FR84",
    "n": "Vaucluse",
    "iso": "FR-84",
    "la": 44.05,
    "lo": 5.21,
    "b": [
      43.67,
      4.66,
      44.43,
      5.75
    ]
  },
  "FR85": {
    "cc": "FR",
    "a": "FR85",
    "n": "Vendée",
    "iso": "FR-85",
    "la": 46.68,
    "lo": -1.47,
    "b": [
      46.28,
      -2.38,
      47.08,
      -0.56
    ]
  },
  "FR86": {
    "cc": "FR",
    "a": "FR86",
    "n": "Vienne",
    "iso": "FR-86",
    "la": 46.61,
    "lo": 0.54,
    "b": [
      46.05,
      -0.11,
      47.16,
      1.19
    ]
  },
  "FR87": {
    "cc": "FR",
    "a": "FR87",
    "n": "Haute-Vienne",
    "iso": "FR-87",
    "la": 45.93,
    "lo": 1.27,
    "b": [
      45.45,
      0.64,
      46.4,
      1.91
    ]
  },
  "FR88": {
    "cc": "FR",
    "a": "FR88",
    "n": "Vosges",
    "iso": "FR-88",
    "la": 48.17,
    "lo": 6.32,
    "b": [
      47.82,
      5.42,
      48.52,
      7.21
    ]
  },
  "FR89": {
    "cc": "FR",
    "a": "FR89",
    "n": "Yonne",
    "iso": "FR-89",
    "la": 47.86,
    "lo": 3.59,
    "b": [
      47.31,
      2.83,
      48.41,
      4.34
    ]
  },
  "FR90": {
    "cc": "FR",
    "a": "FR90",
    "n": "Territoire de Belfort",
    "iso": "FR-90",
    "la": 47.63,
    "lo": 6.96,
    "b": [
      47.43,
      6.76,
      47.82,
      7.15
    ]
  },
  "FR91": {
    "cc": "FR",
    "a": "FR91",
    "n": "Essonne",
    "iso": "FR-91",
    "la": 48.53,
    "lo": 2.25,
    "b": [
      48.28,
      1.92,
      48.78,
      2.58
    ]
  },
  "FR92": {
    "cc": "FR",
    "a": "FR92",
    "n": "Hauts-de-Seine",
    "iso": "FR-92",
    "la": 48.85,
    "lo": 2.24,
    "b": [
      48.73,
      2.15,
      48.96,
      2.33
    ]
  },
  "FR93": {
    "cc": "FR",
    "a": "FR93",
    "n": "Seine-Saint-Denis",
    "iso": "FR-93",
    "la": 48.91,
    "lo": 2.43,
    "b": [
      48.81,
      2.27,
      49.01,
      2.59
    ]
  },
  "FR94": {
    "cc": "FR",
    "a": "FR94",
    "n": "Val-de-Marne",
    "iso": "FR-94",
    "la": 48.78,
    "lo": 2.46,
    "b": [
      48.69,
      2.32,
      48.86,
      2.6
    ]
  },
  "FR95": {
    "cc": "FR",
    "a": "FR95",
    "n": "Val-d'Oise",
    "iso": "FR-95",
    "la": 49.06,
    "lo": 2.1,
    "b": [
      48.88,
      1.62,
      49.23,
      2.58
    ]
  },
  "DEBB": {
    "cc": "DE",
    "a": "DEBB",
    "n": "Brandenburg",
    "iso": "DE-BB",
    "la": 52.45,
    "lo": 13.02,
    "b": [
      51.35,
      11.27,
      53.54,
      14.76
    ]
  },
  "DEBE": {
    "cc": "DE",
    "a": "DEBE",
    "n": "Berlin",
    "iso": "DE-BE",
    "la": 52.5,
    "lo": 13.42,
    "b": [
      52.34,
      13.09,
      52.66,
      13.75
    ]
  },
  "DEBW": {
    "cc": "DE",
    "a": "DEBW",
    "n": "Baden-Württemberg",
    "iso": "DE-BW",
    "la": 48.67,
    "lo": 9,
    "b": [
      47.53,
      7.51,
      49.8,
      10.5
    ]
  },
  "DEBY": {
    "cc": "DE",
    "a": "DEBY",
    "n": "Bayern",
    "iso": "DE-BY",
    "la": 48.92,
    "lo": 11.4,
    "b": [
      47.27,
      8.98,
      50.56,
      13.82
    ]
  },
  "DEHB": {
    "cc": "DE",
    "a": "DEHB",
    "n": "Bremen",
    "iso": "DE-HB",
    "la": 53.32,
    "lo": 8.75,
    "b": [
      53.02,
      8.5,
      53.62,
      8.99
    ]
  },
  "DEHE": {
    "cc": "DE",
    "a": "DEHE",
    "n": "Hessen",
    "iso": "DE-HE",
    "la": 50.53,
    "lo": 9,
    "b": [
      49.4,
      7.77,
      51.66,
      10.23
    ]
  },
  "DEHH": {
    "cc": "DE",
    "a": "DEHH",
    "n": "Hamburg",
    "iso": "DE-HH",
    "la": 53.57,
    "lo": 10.04,
    "b": [
      53.4,
      9.74,
      53.73,
      10.33
    ]
  },
  "DEMV": {
    "cc": "DE",
    "a": "DEMV",
    "n": "Mecklenburg-Vorpommern",
    "iso": "DE-MV",
    "la": 53.9,
    "lo": 12.5,
    "b": [
      53.11,
      10.6,
      54.69,
      14.39
    ]
  },
  "DENI": {
    "cc": "DE",
    "a": "DENI",
    "n": "Niedersachsen",
    "iso": "DE-NI",
    "la": 52.59,
    "lo": 9.12,
    "b": [
      51.29,
      6.66,
      53.89,
      11.58
    ]
  },
  "DENW": {
    "cc": "DE",
    "a": "DENW",
    "n": "Nordrhein-Westfalen",
    "iso": "DE-NW",
    "la": 51.42,
    "lo": 7.66,
    "b": [
      50.32,
      5.85,
      52.52,
      9.46
    ]
  },
  "DERP": {
    "cc": "DE",
    "a": "DERP",
    "n": "Rheinland-Pfalz",
    "iso": "DE-RP",
    "la": 49.95,
    "lo": 7.3,
    "b": [
      48.96,
      6.1,
      50.93,
      8.5
    ]
  },
  "DESH": {
    "cc": "DE",
    "a": "DESH",
    "n": "Schleswig-Holstein",
    "iso": "DE-SH",
    "la": 54.22,
    "lo": 9.6,
    "b": [
      53.36,
      7.88,
      55.07,
      11.31
    ]
  },
  "DESL": {
    "cc": "DE",
    "a": "DESL",
    "n": "Saarland",
    "iso": "DE-SL",
    "la": 49.37,
    "lo": 6.87,
    "b": [
      49.11,
      6.34,
      49.63,
      7.39
    ]
  },
  "DESN": {
    "cc": "DE",
    "a": "DESN",
    "n": "Sachsen",
    "iso": "DE-SN",
    "la": 50.92,
    "lo": 13.46,
    "b": [
      50.16,
      11.9,
      51.67,
      15.02
    ]
  },
  "DEST": {
    "cc": "DE",
    "a": "DEST",
    "n": "Sachsen-Anhalt",
    "iso": "DE-ST",
    "la": 51.99,
    "lo": 11.91,
    "b": [
      50.93,
      10.57,
      53.05,
      13.24
    ]
  },
  "DETH": {
    "cc": "DE",
    "a": "DETH",
    "n": "Thüringen",
    "iso": "DE-TH",
    "la": 50.93,
    "lo": 11.27,
    "b": [
      50.21,
      9.88,
      51.64,
      12.65
    ]
  },
  "NLDR": {
    "cc": "NL",
    "a": "NLDR",
    "n": "Drenthe",
    "iso": "NL-DR",
    "la": 52.91,
    "lo": 6.6,
    "b": [
      52.61,
      6.13,
      53.2,
      7.07
    ]
  },
  "NLFL": {
    "cc": "NL",
    "a": "NLFL",
    "n": "Flevoland",
    "iso": "NL-FL",
    "la": 52.55,
    "lo": 5.56,
    "b": [
      52.26,
      5.1,
      52.84,
      6.02
    ]
  },
  "NLFR": {
    "cc": "NL",
    "a": "NLFR",
    "n": "Friesland",
    "iso": "NL-FR",
    "la": 53.15,
    "lo": 5.65,
    "b": [
      52.79,
      4.88,
      53.51,
      6.43
    ]
  },
  "NLGE": {
    "cc": "NL",
    "a": "NLGE",
    "n": "Gelderland",
    "iso": "NL-GE",
    "la": 52.13,
    "lo": 5.9,
    "b": [
      51.73,
      5,
      52.52,
      6.81
    ]
  },
  "NLGR": {
    "cc": "NL",
    "a": "NLGR",
    "n": "Groningen",
    "iso": "NL-GR",
    "la": 53.2,
    "lo": 6.69,
    "b": [
      52.84,
      6.17,
      53.56,
      7.2
    ]
  },
  "NLLI": {
    "cc": "NL",
    "a": "NLLI",
    "n": "Limburg",
    "iso": "NL-LI",
    "la": 51.27,
    "lo": 5.88,
    "b": [
      50.75,
      5.55,
      51.78,
      6.21
    ]
  },
  "NLNB": {
    "cc": "NL",
    "a": "NLNB",
    "n": "Noord-Brabant",
    "iso": "NL-NB",
    "la": 51.53,
    "lo": 5.12,
    "b": [
      51.22,
      4.19,
      51.84,
      6.05
    ]
  },
  "NLNH": {
    "cc": "NL",
    "a": "NLNH",
    "n": "Noord-Holland",
    "iso": "NL-NH",
    "la": 52.68,
    "lo": 4.94,
    "b": [
      52.17,
      4.5,
      53.19,
      5.37
    ]
  },
  "NLOV": {
    "cc": "NL",
    "a": "NLOV",
    "n": "Overijssel",
    "iso": "NL-OV",
    "la": 52.48,
    "lo": 6.42,
    "b": [
      52.11,
      5.79,
      52.85,
      7.05
    ]
  },
  "NLUT": {
    "cc": "NL",
    "a": "NLUT",
    "n": "Utrecht",
    "iso": "NL-UT",
    "la": 52.11,
    "lo": 5.2,
    "b": [
      51.94,
      4.77,
      52.29,
      5.62
    ]
  },
  "NLZE": {
    "cc": "NL",
    "a": "NLZE",
    "n": "Zeeland",
    "iso": "NL-ZE",
    "la": 51.48,
    "lo": 3.82,
    "b": [
      51.21,
      3.35,
      51.75,
      4.28
    ]
  },
  "NLZH": {
    "cc": "NL",
    "a": "NLZH",
    "n": "Zuid-Holland",
    "iso": "NL-ZH",
    "la": 51.99,
    "lo": 4.52,
    "b": [
      51.64,
      3.86,
      52.34,
      5.18
    ]
  },
  "BEBRU": {
    "cc": "BE",
    "a": "BEBRU",
    "n": "Brussels",
    "iso": "BE-BRU",
    "la": 50.83,
    "lo": 4.37,
    "b": [
      50.76,
      4.25,
      50.91,
      4.48
    ]
  },
  "BEVAN": {
    "cc": "BE",
    "a": "BEVAN",
    "n": "Antwerp",
    "iso": "BE-VAN",
    "la": 51.25,
    "lo": 4.72,
    "b": [
      50.99,
      4.18,
      51.5,
      5.26
    ]
  },
  "BEVBR": {
    "cc": "BE",
    "a": "BEVBR",
    "n": "Flemish Brabant",
    "iso": "BE-VBR",
    "la": 50.87,
    "lo": 4.54,
    "b": [
      50.69,
      3.89,
      51.05,
      5.19
    ]
  },
  "BEVLI": {
    "cc": "BE",
    "a": "BEVLI",
    "n": "Limburg",
    "iso": "BE-VLI",
    "la": 51,
    "lo": 5.45,
    "b": [
      50.7,
      4.98,
      51.29,
      5.91
    ]
  },
  "BEVOV": {
    "cc": "BE",
    "a": "BEVOV",
    "n": "East Flanders",
    "iso": "BE-VOV",
    "la": 51.05,
    "lo": 3.83,
    "b": [
      50.72,
      3.33,
      51.37,
      4.33
    ]
  },
  "BEVWV": {
    "cc": "BE",
    "a": "BEVWV",
    "n": "West Flanders",
    "iso": "BE-VWV",
    "la": 51.04,
    "lo": 3.02,
    "b": [
      50.7,
      2.52,
      51.38,
      3.52
    ]
  },
  "BEWBR": {
    "cc": "BE",
    "a": "BEWBR",
    "n": "Walloon Brabant",
    "iso": "BE-WBR",
    "la": 50.67,
    "lo": 4.56,
    "b": [
      50.53,
      4.09,
      50.81,
      5.02
    ]
  },
  "BEWHT": {
    "cc": "BE",
    "a": "BEWHT",
    "n": "Hainaut",
    "iso": "BE-WHT",
    "la": 50.37,
    "lo": 3.73,
    "b": [
      49.93,
      2.84,
      50.81,
      4.62
    ]
  },
  "BEWLG": {
    "cc": "BE",
    "a": "BEWLG",
    "n": "Liege",
    "iso": "BE-WLG",
    "la": 50.47,
    "lo": 5.68,
    "b": [
      50.12,
      4.98,
      50.81,
      6.37
    ]
  },
  "BEWLX": {
    "cc": "BE",
    "a": "BEWLX",
    "n": "Luxembourg",
    "iso": "BE-WLX",
    "la": 49.97,
    "lo": 5.5,
    "b": [
      49.5,
      4.97,
      50.43,
      6.03
    ]
  },
  "BEWNA": {
    "cc": "BE",
    "a": "BEWNA",
    "n": "Namur",
    "iso": "BE-WNA",
    "la": 50.22,
    "lo": 4.85,
    "b": [
      49.78,
      4.29,
      50.65,
      5.4
    ]
  },
  "ESA": {
    "cc": "ES",
    "a": "ESA",
    "n": "Alicante",
    "iso": "ES-A",
    "la": 38.36,
    "lo": -0.43,
    "b": [
      37.84,
      -1.08,
      38.88,
      0.23
    ]
  },
  "ESAB": {
    "cc": "ES",
    "a": "ESAB",
    "n": "Albacete",
    "iso": "ES-AB",
    "la": 38.72,
    "lo": -1.89,
    "b": [
      38.02,
      -2.88,
      39.42,
      -0.9
    ]
  },
  "ESAL": {
    "cc": "ES",
    "a": "ESAL",
    "n": "Almería",
    "iso": "ES-AL",
    "la": 37.3,
    "lo": -2.39,
    "b": [
      36.68,
      -3.14,
      37.92,
      -1.64
    ]
  },
  "ESAV": {
    "cc": "ES",
    "a": "ESAV",
    "n": "Ávila",
    "iso": "ES-AV",
    "la": 40.63,
    "lo": -4.94,
    "b": [
      40.09,
      -5.73,
      41.16,
      -4.16
    ]
  },
  "ESB": {
    "cc": "ES",
    "a": "ESB",
    "n": "Barcelona",
    "iso": "ES-B",
    "la": 41.76,
    "lo": 2.08,
    "b": [
      41.19,
      1.37,
      42.32,
      2.78
    ]
  },
  "ESBA": {
    "cc": "ES",
    "a": "ESBA",
    "n": "Badajoz",
    "iso": "ES-BA",
    "la": 38.7,
    "lo": -6.01,
    "b": [
      37.94,
      -7.36,
      39.45,
      -4.66
    ]
  },
  "ESBI": {
    "cc": "ES",
    "a": "ESBI",
    "n": "Bizkaia",
    "iso": "ES-BI",
    "la": 43.24,
    "lo": -2.92,
    "b": [
      43.02,
      -3.44,
      43.45,
      -2.41
    ]
  },
  "ESBU": {
    "cc": "ES",
    "a": "ESBU",
    "n": "Burgos",
    "iso": "ES-BU",
    "la": 42.33,
    "lo": -3.42,
    "b": [
      41.46,
      -4.33,
      43.2,
      -2.51
    ]
  },
  "ESC": {
    "cc": "ES",
    "a": "ESC",
    "n": "La Coruña",
    "iso": "ES-C",
    "la": 43.16,
    "lo": -8.48,
    "b": [
      42.53,
      -9.29,
      43.79,
      -7.67
    ]
  },
  "ESCA": {
    "cc": "ES",
    "a": "ESCA",
    "n": "Cádiz",
    "iso": "ES-CA",
    "la": 36.53,
    "lo": -5.76,
    "b": [
      36.01,
      -6.44,
      37.05,
      -5.08
    ]
  },
  "ESCC": {
    "cc": "ES",
    "a": "ESCC",
    "n": "Cáceres",
    "iso": "ES-CC",
    "la": 39.75,
    "lo": -6.25,
    "b": [
      39.03,
      -7.56,
      40.48,
      -4.94
    ]
  },
  "ESCE": {
    "cc": "ES",
    "a": "ESCE",
    "n": "Ceuta",
    "iso": "ES-CE",
    "la": 35.89,
    "lo": -5.34,
    "b": [
      35.85,
      -5.4,
      35.93,
      -5.28
    ]
  },
  "ESCO": {
    "cc": "ES",
    "a": "ESCO",
    "n": "Córdoba",
    "iso": "ES-CO",
    "la": 37.96,
    "lo": -4.79,
    "b": [
      37.19,
      -5.58,
      38.73,
      -4
    ]
  },
  "ESCR": {
    "cc": "ES",
    "a": "ESCR",
    "n": "Ciudad Real",
    "iso": "ES-CR",
    "la": 38.97,
    "lo": -3.84,
    "b": [
      38.35,
      -5.04,
      39.58,
      -2.64
    ]
  },
  "ESCS": {
    "cc": "ES",
    "a": "ESCS",
    "n": "Castellón",
    "iso": "ES-CS",
    "la": 40.25,
    "lo": -0.16,
    "b": [
      39.72,
      -0.84,
      40.78,
      0.52
    ]
  },
  "ESCU": {
    "cc": "ES",
    "a": "ESCU",
    "n": "Cuenca",
    "iso": "ES-CU",
    "la": 39.94,
    "lo": -2.16,
    "b": [
      39.23,
      -3.17,
      40.66,
      -1.15
    ]
  },
  "ESGC": {
    "cc": "ES",
    "a": "ESGC",
    "n": "Las Palmas",
    "iso": "ES-GC",
    "la": 28.51,
    "lo": -14.62,
    "b": [
      27.73,
      -15.82,
      29.29,
      -13.42
    ]
  },
  "ESGI": {
    "cc": "ES",
    "a": "ESGI",
    "n": "Gerona",
    "iso": "ES-GI",
    "la": 42.07,
    "lo": 2.51,
    "b": [
      41.65,
      1.71,
      42.49,
      3.32
    ]
  },
  "ESGR": {
    "cc": "ES",
    "a": "ESGR",
    "n": "Granada",
    "iso": "ES-GR",
    "la": 37.39,
    "lo": -3.26,
    "b": [
      36.7,
      -4.32,
      38.08,
      -2.21
    ]
  },
  "ESGU": {
    "cc": "ES",
    "a": "ESGU",
    "n": "Guadalajara",
    "iso": "ES-GU",
    "la": 40.74,
    "lo": -2.54,
    "b": [
      40.16,
      -3.55,
      41.32,
      -1.54
    ]
  },
  "ESH": {
    "cc": "ES",
    "a": "ESH",
    "n": "Huelva",
    "iso": "ES-H",
    "la": 37.51,
    "lo": -6.82,
    "b": [
      36.81,
      -7.53,
      38.21,
      -6.12
    ]
  },
  "ESHU": {
    "cc": "ES",
    "a": "ESHU",
    "n": "Huesca",
    "iso": "ES-HU",
    "la": 42.14,
    "lo": -0.08,
    "b": [
      41.35,
      -0.92,
      42.92,
      0.77
    ]
  },
  "ESJ": {
    "cc": "ES",
    "a": "ESJ",
    "n": "Jaén",
    "iso": "ES-J",
    "la": 37.96,
    "lo": -3.36,
    "b": [
      37.38,
      -4.28,
      38.53,
      -2.43
    ]
  },
  "ESL": {
    "cc": "ES",
    "a": "ESL",
    "n": "Lérida",
    "iso": "ES-L",
    "la": 42.04,
    "lo": 1.08,
    "b": [
      41.23,
      0.32,
      42.85,
      1.84
    ]
  },
  "ESLE": {
    "cc": "ES",
    "a": "ESLE",
    "n": "León",
    "iso": "ES-LE",
    "la": 42.64,
    "lo": -5.9,
    "b": [
      42.03,
      -7.07,
      43.24,
      -4.73
    ]
  },
  "ESLO": {
    "cc": "ES",
    "a": "ESLO",
    "n": "La Rioja",
    "iso": "ES-LO",
    "la": 42.28,
    "lo": -2.41,
    "b": [
      41.92,
      -3.12,
      42.64,
      -1.69
    ]
  },
  "ESLU": {
    "cc": "ES",
    "a": "ESLU",
    "n": "Lugo",
    "iso": "ES-LU",
    "la": 43.04,
    "lo": -7.41,
    "b": [
      42.33,
      -8,
      43.75,
      -6.83
    ]
  },
  "ESM": {
    "cc": "ES",
    "a": "ESM",
    "n": "Madrid",
    "iso": "ES-M",
    "la": 40.53,
    "lo": -3.82,
    "b": [
      39.89,
      -4.57,
      41.16,
      -3.06
    ]
  },
  "ESMA": {
    "cc": "ES",
    "a": "ESMA",
    "n": "Málaga",
    "iso": "ES-MA",
    "la": 36.79,
    "lo": -4.69,
    "b": [
      36.3,
      -5.61,
      37.28,
      -3.77
    ]
  },
  "ESML": {
    "cc": "ES",
    "a": "ESML",
    "n": "Melilla",
    "iso": "ES-ML",
    "la": 35.3,
    "lo": -2.94,
    "b": [
      35.27,
      -2.97,
      35.33,
      -2.91
    ]
  },
  "ESMU": {
    "cc": "ES",
    "a": "ESMU",
    "n": "Murcia",
    "iso": "ES-MU",
    "la": 38.07,
    "lo": -1.52,
    "b": [
      37.38,
      -2.34,
      38.75,
      -0.7
    ]
  },
  "ESNA": {
    "cc": "ES",
    "a": "ESNA",
    "n": "Navarra",
    "iso": "ES-NA",
    "la": 42.61,
    "lo": -1.62,
    "b": [
      41.91,
      -2.49,
      43.3,
      -0.74
    ]
  },
  "ESO": {
    "cc": "ES",
    "a": "ESO",
    "n": "Asturias",
    "iso": "ES-O",
    "la": 43.28,
    "lo": -5.84,
    "b": [
      42.89,
      -7.17,
      43.66,
      -4.51
    ]
  },
  "ESOR": {
    "cc": "ES",
    "a": "ESOR",
    "n": "Orense",
    "iso": "ES-OR",
    "la": 42.2,
    "lo": -7.54,
    "b": [
      41.81,
      -8.34,
      42.58,
      -6.74
    ]
  },
  "ESP": {
    "cc": "ES",
    "a": "ESP",
    "n": "Palencia",
    "iso": "ES-P",
    "la": 42.41,
    "lo": -4.46,
    "b": [
      41.76,
      -5.03,
      43.05,
      -3.89
    ]
  },
  "ESPM": {
    "cc": "ES",
    "a": "ESPM",
    "n": "Baleares",
    "iso": "ES-PM",
    "la": 39.36,
    "lo": 2.78,
    "b": [
      38.64,
      1.21,
      40.08,
      4.34
    ]
  },
  "ESPO": {
    "cc": "ES",
    "a": "ESPO",
    "n": "Pontevedra",
    "iso": "ES-PO",
    "la": 42.37,
    "lo": -8.4,
    "b": [
      41.89,
      -8.94,
      42.85,
      -7.87
    ]
  },
  "ESS": {
    "cc": "ES",
    "a": "ESS",
    "n": "Cantabria",
    "iso": "ES-S",
    "la": 43.14,
    "lo": -3.99,
    "b": [
      42.76,
      -4.84,
      43.52,
      -3.15
    ]
  },
  "ESSA": {
    "cc": "ES",
    "a": "ESSA",
    "n": "Salamanca",
    "iso": "ES-SA",
    "la": 40.77,
    "lo": -6.02,
    "b": [
      40.24,
      -6.94,
      41.3,
      -5.1
    ]
  },
  "ESSE": {
    "cc": "ES",
    "a": "ESSE",
    "n": "Sevilla",
    "iso": "ES-SE",
    "la": 37.52,
    "lo": -5.59,
    "b": [
      36.84,
      -6.53,
      38.19,
      -4.65
    ]
  },
  "ESSG": {
    "cc": "ES",
    "a": "ESSG",
    "n": "Segovia",
    "iso": "ES-SG",
    "la": 41.11,
    "lo": -3.95,
    "b": [
      40.63,
      -4.71,
      41.58,
      -3.2
    ]
  },
  "ESSO": {
    "cc": "ES",
    "a": "ESSO",
    "n": "Soria",
    "iso": "ES-SO",
    "la": 41.6,
    "lo": -2.66,
    "b": [
      41.06,
      -3.54,
      42.14,
      -1.79
    ]
  },
  "ESSS": {
    "cc": "ES",
    "a": "ESSS",
    "n": "Gipuzkoa",
    "iso": "ES-SS",
    "la": 43.15,
    "lo": -2.17,
    "b": [
      42.9,
      -2.6,
      43.4,
      -1.75
    ]
  },
  "EST": {
    "cc": "ES",
    "a": "EST",
    "n": "Tarragona",
    "iso": "ES-T",
    "la": 41.06,
    "lo": 0.9,
    "b": [
      40.53,
      0.17,
      41.58,
      1.63
    ]
  },
  "ESTE": {
    "cc": "ES",
    "a": "ESTE",
    "n": "Teruel",
    "iso": "ES-TE",
    "la": 40.6,
    "lo": -0.76,
    "b": [
      39.85,
      -1.81,
      41.35,
      0.29
    ]
  },
  "ESTF": {
    "cc": "ES",
    "a": "ESTF",
    "n": "Santa Cruz de Tenerife",
    "iso": "ES-TF",
    "la": 28.25,
    "lo": -17.15,
    "b": [
      27.64,
      -18.17,
      28.86,
      -16.12
    ]
  },
  "ESTO": {
    "cc": "ES",
    "a": "ESTO",
    "n": "Toledo",
    "iso": "ES-TO",
    "la": 39.78,
    "lo": -4.15,
    "b": [
      39.26,
      -5.39,
      40.31,
      -2.91
    ]
  },
  "ESV": {
    "cc": "ES",
    "a": "ESV",
    "n": "Valencia",
    "iso": "ES-V",
    "la": 39.45,
    "lo": -0.77,
    "b": [
      38.69,
      -1.52,
      40.2,
      -0.03
    ]
  },
  "ESVA": {
    "cc": "ES",
    "a": "ESVA",
    "n": "Valladolid",
    "iso": "ES-VA",
    "la": 41.71,
    "lo": -4.75,
    "b": [
      41.1,
      -5.52,
      42.31,
      -3.98
    ]
  },
  "ESVI": {
    "cc": "ES",
    "a": "ESVI",
    "n": "Álava",
    "iso": "ES-VI",
    "la": 42.86,
    "lo": -2.76,
    "b": [
      42.5,
      -3.28,
      43.21,
      -2.24
    ]
  },
  "ESZ": {
    "cc": "ES",
    "a": "ESZ",
    "n": "Zaragoza",
    "iso": "ES-Z",
    "la": 41.84,
    "lo": -0.89,
    "b": [
      40.94,
      -2.17,
      42.74,
      0.38
    ]
  },
  "ESZA": {
    "cc": "ES",
    "a": "ESZA",
    "n": "Zamora",
    "iso": "ES-ZA",
    "la": 41.69,
    "lo": -6.13,
    "b": [
      41.12,
      -7.03,
      42.25,
      -5.23
    ]
  },
  "ITAG": {
    "cc": "IT",
    "a": "ITAG",
    "n": "Agrigento",
    "iso": "IT-AG",
    "la": 36.62,
    "lo": 13.29,
    "b": [
      35.49,
      12.53,
      37.74,
      14.04
    ]
  },
  "ITAL": {
    "cc": "IT",
    "a": "ITAL",
    "n": "Alessandria",
    "iso": "IT-AL",
    "la": 44.84,
    "lo": 8.66,
    "b": [
      44.48,
      8.11,
      45.2,
      9.21
    ]
  },
  "ITAN": {
    "cc": "IT",
    "a": "ITAN",
    "n": "Ancona",
    "iso": "IT-AN",
    "la": 43.48,
    "lo": 13.2,
    "b": [
      43.21,
      12.75,
      43.75,
      13.65
    ]
  },
  "ITAO": {
    "cc": "IT",
    "a": "ITAO",
    "n": "Aoste",
    "iso": "IT-AO",
    "la": 45.72,
    "lo": 7.35,
    "b": [
      45.47,
      6.78,
      45.98,
      7.92
    ]
  },
  "ITAP": {
    "cc": "IT",
    "a": "ITAP",
    "n": "Ascoli Piceno",
    "iso": "IT-AP",
    "la": 42.89,
    "lo": 13.55,
    "b": [
      42.69,
      13.19,
      43.08,
      13.91
    ]
  },
  "ITAQ": {
    "cc": "IT",
    "a": "ITAQ",
    "n": "L'Aquila",
    "iso": "IT-AQ",
    "la": 42.15,
    "lo": 13.62,
    "b": [
      41.69,
      13.01,
      42.6,
      14.23
    ]
  },
  "ITAR": {
    "cc": "IT",
    "a": "ITAR",
    "n": "Arezzo",
    "iso": "IT-AR",
    "la": 43.52,
    "lo": 11.88,
    "b": [
      43.16,
      11.4,
      43.88,
      12.36
    ]
  },
  "ITAT": {
    "cc": "IT",
    "a": "ITAT",
    "n": "Asti",
    "iso": "IT-AT",
    "la": 44.83,
    "lo": 8.2,
    "b": [
      44.52,
      7.89,
      45.13,
      8.5
    ]
  },
  "ITAV": {
    "cc": "IT",
    "a": "ITAV",
    "n": "Avellino",
    "iso": "IT-AV",
    "la": 41,
    "lo": 15.08,
    "b": [
      40.71,
      14.57,
      41.29,
      15.58
    ]
  },
  "ITBA": {
    "cc": "IT",
    "a": "ITBA",
    "n": "Bari",
    "iso": "IT-BA",
    "la": 40.97,
    "lo": 16.8,
    "b": [
      40.69,
      16.2,
      41.24,
      17.4
    ]
  },
  "ITBG": {
    "cc": "IT",
    "a": "ITBG",
    "n": "Bergamo",
    "iso": "IT-BG",
    "la": 45.76,
    "lo": 9.86,
    "b": [
      45.42,
      9.45,
      46.09,
      10.26
    ]
  },
  "ITBI": {
    "cc": "IT",
    "a": "ITBI",
    "n": "Biella",
    "iso": "IT-BI",
    "la": 45.57,
    "lo": 8.08,
    "b": [
      45.38,
      7.88,
      45.76,
      8.29
    ]
  },
  "ITBL": {
    "cc": "IT",
    "a": "ITBL",
    "n": "Belluno",
    "iso": "IT-BL",
    "la": 46.28,
    "lo": 12.22,
    "b": [
      45.88,
      11.68,
      46.68,
      12.76
    ]
  },
  "ITBN": {
    "cc": "IT",
    "a": "ITBN",
    "n": "Benevento",
    "iso": "IT-BN",
    "la": 41.22,
    "lo": 14.75,
    "b": [
      40.97,
      14.36,
      41.48,
      15.14
    ]
  },
  "ITBO": {
    "cc": "IT",
    "a": "ITBO",
    "n": "Bologna",
    "iso": "IT-BO",
    "la": 44.44,
    "lo": 11.32,
    "b": [
      44.07,
      10.81,
      44.8,
      11.82
    ]
  },
  "ITBR": {
    "cc": "IT",
    "a": "ITBR",
    "n": "Brindisi",
    "iso": "IT-BR",
    "la": 40.64,
    "lo": 17.71,
    "b": [
      40.38,
      17.32,
      40.89,
      18.1
    ]
  },
  "ITBS": {
    "cc": "IT",
    "a": "ITBS",
    "n": "Brescia",
    "iso": "IT-BS",
    "la": 45.78,
    "lo": 10.35,
    "b": [
      45.2,
      9.86,
      46.35,
      10.84
    ]
  },
  "ITBT": {
    "cc": "IT",
    "a": "ITBT",
    "n": "Barletta-Andria Trani",
    "iso": "IT-BT",
    "la": 41.18,
    "lo": 16.2,
    "b": [
      40.9,
      15.86,
      41.45,
      16.54
    ]
  },
  "ITBZ": {
    "cc": "IT",
    "a": "ITBZ",
    "n": "Bozen",
    "iso": "IT-BZ",
    "la": 46.66,
    "lo": 11.42,
    "b": [
      46.22,
      10.37,
      47.09,
      12.47
    ]
  },
  "ITCA": {
    "cc": "IT",
    "a": "ITCA",
    "n": "Cagliari",
    "iso": "IT-CA",
    "la": 39.39,
    "lo": 9.13,
    "b": [
      38.86,
      8.6,
      39.92,
      9.65
    ]
  },
  "ITCB": {
    "cc": "IT",
    "a": "ITCB",
    "n": "Campobasso",
    "iso": "IT-CB",
    "la": 41.72,
    "lo": 14.77,
    "b": [
      41.37,
      14.38,
      42.08,
      15.16
    ]
  },
  "ITCE": {
    "cc": "IT",
    "a": "ITCE",
    "n": "Caserta",
    "iso": "IT-CE",
    "la": 41.22,
    "lo": 14.14,
    "b": [
      40.94,
      13.74,
      41.5,
      14.53
    ]
  },
  "ITCH": {
    "cc": "IT",
    "a": "ITCH",
    "n": "Chieti",
    "iso": "IT-CH",
    "la": 42.11,
    "lo": 14.42,
    "b": [
      41.77,
      14.07,
      42.45,
      14.76
    ]
  },
  "ITCI": {
    "cc": "IT",
    "a": "ITCI",
    "n": "Carbonia-Iglesias",
    "iso": "IT-CI",
    "la": 39.22,
    "lo": 8.54,
    "b": [
      38.95,
      8.22,
      39.48,
      8.85
    ]
  },
  "ITCL": {
    "cc": "IT",
    "a": "ITCL",
    "n": "Caltanissetta",
    "iso": "IT-CL",
    "la": 37.36,
    "lo": 14.06,
    "b": [
      37,
      13.64,
      37.73,
      14.47
    ]
  },
  "ITCN": {
    "cc": "IT",
    "a": "ITCN",
    "n": "Cuneo",
    "iso": "IT-CN",
    "la": 44.48,
    "lo": 7.56,
    "b": [
      44.09,
      6.84,
      44.86,
      8.27
    ]
  },
  "ITCO": {
    "cc": "IT",
    "a": "ITCO",
    "n": "Como",
    "iso": "IT-CO",
    "la": 45.95,
    "lo": 9.17,
    "b": [
      45.65,
      8.9,
      46.24,
      9.44
    ]
  },
  "ITCR": {
    "cc": "IT",
    "a": "ITCR",
    "n": "Cremona",
    "iso": "IT-CR",
    "la": 45.22,
    "lo": 10.02,
    "b": [
      44.92,
      9.46,
      45.51,
      10.57
    ]
  },
  "ITCS": {
    "cc": "IT",
    "a": "ITCS",
    "n": "Cosenza",
    "iso": "IT-CS",
    "la": 39.6,
    "lo": 16.38,
    "b": [
      39.05,
      15.75,
      40.14,
      17.02
    ]
  },
  "ITCT": {
    "cc": "IT",
    "a": "ITCT",
    "n": "Catania",
    "iso": "IT-CT",
    "la": 37.5,
    "lo": 14.81,
    "b": [
      37.05,
      14.35,
      37.96,
      15.26
    ]
  },
  "ITCZ": {
    "cc": "IT",
    "a": "ITCZ",
    "n": "Catanzaro",
    "iso": "IT-CZ",
    "la": 38.83,
    "lo": 16.5,
    "b": [
      38.47,
      16.1,
      39.19,
      16.9
    ]
  },
  "ITEN": {
    "cc": "IT",
    "a": "ITEN",
    "n": "Enna",
    "iso": "IT-EN",
    "la": 37.59,
    "lo": 14.46,
    "b": [
      37.29,
      14.07,
      37.88,
      14.84
    ]
  },
  "ITFC": {
    "cc": "IT",
    "a": "ITFC",
    "n": "Forlì-Cesena",
    "iso": "IT-FC",
    "la": 44.04,
    "lo": 12.06,
    "b": [
      43.75,
      11.65,
      44.33,
      12.46
    ]
  },
  "ITFE": {
    "cc": "IT",
    "a": "ITFE",
    "n": "Ferrara",
    "iso": "IT-FE",
    "la": 44.77,
    "lo": 11.81,
    "b": [
      44.55,
      11.23,
      44.99,
      12.39
    ]
  },
  "ITFG": {
    "cc": "IT",
    "a": "ITFG",
    "n": "Foggia",
    "iso": "IT-FG",
    "la": 41.5,
    "lo": 15.56,
    "b": [
      41.06,
      14.93,
      41.94,
      16.19
    ]
  },
  "ITFI": {
    "cc": "IT",
    "a": "ITFI",
    "n": "Firenze",
    "iso": "IT-FI",
    "la": 43.84,
    "lo": 11.23,
    "b": [
      43.45,
      10.71,
      44.23,
      11.75
    ]
  },
  "ITFM": {
    "cc": "IT",
    "a": "ITFM",
    "n": "Fermo",
    "iso": "IT-FM",
    "la": 43.09,
    "lo": 13.54,
    "b": [
      42.89,
      13.22,
      43.29,
      13.85
    ]
  },
  "ITFR": {
    "cc": "IT",
    "a": "ITFR",
    "n": "Frosinone",
    "iso": "IT-FR",
    "la": 41.63,
    "lo": 13.51,
    "b": [
      41.31,
      13,
      41.95,
      14.01
    ]
  },
  "ITGE": {
    "cc": "IT",
    "a": "ITGE",
    "n": "Genova",
    "iso": "IT-GE",
    "la": 44.45,
    "lo": 9.07,
    "b": [
      44.22,
      8.56,
      44.68,
      9.57
    ]
  },
  "ITGO": {
    "cc": "IT",
    "a": "ITGO",
    "n": "Gorizia",
    "iso": "IT-GO",
    "la": 45.85,
    "lo": 13.5,
    "b": [
      45.68,
      13.38,
      46.01,
      13.62
    ]
  },
  "ITGR": {
    "cc": "IT",
    "a": "ITGR",
    "n": "Grosseto",
    "iso": "IT-GR",
    "la": 42.76,
    "lo": 11.26,
    "b": [
      42.32,
      10.71,
      43.19,
      11.81
    ]
  },
  "ITIM": {
    "cc": "IT",
    "a": "ITIM",
    "n": "Imperia",
    "iso": "IT-IM",
    "la": 43.96,
    "lo": 7.81,
    "b": [
      43.78,
      7.48,
      44.14,
      8.13
    ]
  },
  "ITIS": {
    "cc": "IT",
    "a": "ITIS",
    "n": "Isernia",
    "iso": "IT-IS",
    "la": 41.65,
    "lo": 14.24,
    "b": [
      41.39,
      13.95,
      41.91,
      14.52
    ]
  },
  "ITKR": {
    "cc": "IT",
    "a": "ITKR",
    "n": "Crotene",
    "iso": "IT-KR",
    "la": 39.19,
    "lo": 16.91,
    "b": [
      38.9,
      16.61,
      39.48,
      17.21
    ]
  },
  "ITLC": {
    "cc": "IT",
    "a": "ITLC",
    "n": "Lecco",
    "iso": "IT-LC",
    "la": 45.91,
    "lo": 9.4,
    "b": [
      45.65,
      9.25,
      46.16,
      9.54
    ]
  },
  "ITLE": {
    "cc": "IT",
    "a": "ITLE",
    "n": "Lecce",
    "iso": "IT-LE",
    "la": 40.16,
    "lo": 18.14,
    "b": [
      39.8,
      17.76,
      40.52,
      18.52
    ]
  },
  "ITLI": {
    "cc": "IT",
    "a": "ITLI",
    "n": "Livorno",
    "iso": "IT-LI",
    "la": 42.98,
    "lo": 10.29,
    "b": [
      42.32,
      9.78,
      43.64,
      10.79
    ]
  },
  "ITLO": {
    "cc": "IT",
    "a": "ITLO",
    "n": "Lodi",
    "iso": "IT-LO",
    "la": 45.27,
    "lo": 9.61,
    "b": [
      45.07,
      9.31,
      45.47,
      9.9
    ]
  },
  "ITLT": {
    "cc": "IT",
    "a": "ITLT",
    "n": "Latina",
    "iso": "IT-LT",
    "la": 41.25,
    "lo": 13.22,
    "b": [
      40.79,
      12.56,
      41.71,
      13.87
    ]
  },
  "ITLU": {
    "cc": "IT",
    "a": "ITLU",
    "n": "Lucca",
    "iso": "IT-LU",
    "la": 44.02,
    "lo": 10.44,
    "b": [
      43.76,
      10.14,
      44.28,
      10.74
    ]
  },
  "ITMB": {
    "cc": "IT",
    "a": "ITMB",
    "n": "Monza e Brianza",
    "iso": "IT-MB",
    "la": 45.64,
    "lo": 9.28,
    "b": [
      45.54,
      9.05,
      45.74,
      9.5
    ]
  },
  "ITMC": {
    "cc": "IT",
    "a": "ITMC",
    "n": "Macerata",
    "iso": "IT-MC",
    "la": 43.15,
    "lo": 13.29,
    "b": [
      42.82,
      12.83,
      43.48,
      13.75
    ]
  },
  "ITME": {
    "cc": "IT",
    "a": "ITME",
    "n": "Messina",
    "iso": "IT-ME",
    "la": 38.31,
    "lo": 14.92,
    "b": [
      37.8,
      14.18,
      38.81,
      15.65
    ]
  },
  "ITMI": {
    "cc": "IT",
    "a": "ITMI",
    "n": "Milano",
    "iso": "IT-MI",
    "la": 45.46,
    "lo": 9.12,
    "b": [
      45.27,
      8.71,
      45.65,
      9.53
    ]
  },
  "ITMN": {
    "cc": "IT",
    "a": "ITMN",
    "n": "Mantova",
    "iso": "IT-MN",
    "la": 45.17,
    "lo": 10.87,
    "b": [
      44.91,
      10.32,
      45.42,
      11.42
    ]
  },
  "ITMO": {
    "cc": "IT",
    "a": "ITMO",
    "n": "Modena",
    "iso": "IT-MO",
    "la": 44.54,
    "lo": 10.92,
    "b": [
      44.11,
      10.47,
      44.96,
      11.37
    ]
  },
  "ITMS": {
    "cc": "IT",
    "a": "ITMS",
    "n": "Massa-Carrara",
    "iso": "IT-MS",
    "la": 44.23,
    "lo": 9.97,
    "b": [
      43.98,
      9.69,
      44.48,
      10.25
    ]
  },
  "ITMT": {
    "cc": "IT",
    "a": "ITMT",
    "n": "Matera",
    "iso": "IT-MT",
    "la": 40.45,
    "lo": 16.4,
    "b": [
      40.06,
      15.94,
      40.84,
      16.86
    ]
  },
  "ITNA": {
    "cc": "IT",
    "a": "ITNA",
    "n": "Napoli",
    "iso": "IT-NA",
    "la": 40.8,
    "lo": 14.26,
    "b": [
      40.57,
      13.85,
      41.02,
      14.67
    ]
  },
  "ITNO": {
    "cc": "IT",
    "a": "ITNO",
    "n": "Novara",
    "iso": "IT-NO",
    "la": 45.58,
    "lo": 8.57,
    "b": [
      45.3,
      8.31,
      45.87,
      8.83
    ]
  },
  "ITNU": {
    "cc": "IT",
    "a": "ITNU",
    "n": "Nuoro",
    "iso": "IT-NU",
    "la": 40.27,
    "lo": 9.22,
    "b": [
      39.83,
      8.61,
      40.7,
      9.83
    ]
  },
  "ITOG": {
    "cc": "IT",
    "a": "ITOG",
    "n": "Ogliastra",
    "iso": "IT-OG",
    "la": 39.89,
    "lo": 9.5,
    "b": [
      39.55,
      9.27,
      40.22,
      9.73
    ]
  },
  "ITOR": {
    "cc": "IT",
    "a": "ITOR",
    "n": "Oristrano",
    "iso": "IT-OR",
    "la": 40.03,
    "lo": 8.77,
    "b": [
      39.63,
      8.38,
      40.42,
      9.16
    ]
  },
  "ITOT": {
    "cc": "IT",
    "a": "ITOT",
    "n": "Olbia-Tempio",
    "iso": "IT-OT",
    "la": 40.9,
    "lo": 9.28,
    "b": [
      40.54,
      8.81,
      41.26,
      9.75
    ]
  },
  "ITPA": {
    "cc": "IT",
    "a": "ITPA",
    "n": "Palermo",
    "iso": "IT-PA",
    "la": 38.13,
    "lo": 13.61,
    "b": [
      37.54,
      12.94,
      38.72,
      14.29
    ]
  },
  "ITPC": {
    "cc": "IT",
    "a": "ITPC",
    "n": "Piacenza",
    "iso": "IT-PC",
    "la": 44.85,
    "lo": 9.64,
    "b": [
      44.55,
      9.2,
      45.14,
      10.07
    ]
  },
  "ITPD": {
    "cc": "IT",
    "a": "ITPD",
    "n": "Padova",
    "iso": "IT-PD",
    "la": 45.4,
    "lo": 11.8,
    "b": [
      45.1,
      11.4,
      45.69,
      12.2
    ]
  },
  "ITPE": {
    "cc": "IT",
    "a": "ITPE",
    "n": "Pescara",
    "iso": "IT-PE",
    "la": 42.32,
    "lo": 14.02,
    "b": [
      42.08,
      13.77,
      42.55,
      14.26
    ]
  },
  "ITPG": {
    "cc": "IT",
    "a": "ITPG",
    "n": "Perugia",
    "iso": "IT-PG",
    "la": 43.12,
    "lo": 12.59,
    "b": [
      42.6,
      11.92,
      43.63,
      13.26
    ]
  },
  "ITPI": {
    "cc": "IT",
    "a": "ITPI",
    "n": "Pisa",
    "iso": "IT-PI",
    "la": 43.47,
    "lo": 10.64,
    "b": [
      43.11,
      10.26,
      43.82,
      11.01
    ]
  },
  "ITPN": {
    "cc": "IT",
    "a": "ITPN",
    "n": "Pordenone",
    "iso": "IT-PN",
    "la": 46.1,
    "lo": 12.66,
    "b": [
      45.8,
      12.34,
      46.4,
      12.98
    ]
  },
  "ITPO": {
    "cc": "IT",
    "a": "ITPO",
    "n": "Prato",
    "iso": "IT-PO",
    "la": 43.94,
    "lo": 11.09,
    "b": [
      43.76,
      10.96,
      44.11,
      11.21
    ]
  },
  "ITPR": {
    "cc": "IT",
    "a": "ITPR",
    "n": "Parma",
    "iso": "IT-PR",
    "la": 44.7,
    "lo": 9.97,
    "b": [
      44.34,
      9.44,
      45.05,
      10.5
    ]
  },
  "ITPT": {
    "cc": "IT",
    "a": "ITPT",
    "n": "Pistoia",
    "iso": "IT-PT",
    "la": 43.98,
    "lo": 10.84,
    "b": [
      43.8,
      10.61,
      44.16,
      11.06
    ]
  },
  "ITPU": {
    "cc": "IT",
    "a": "ITPU",
    "n": "Pesaro e Urbino",
    "iso": "IT-PU",
    "la": 43.7,
    "lo": 12.68,
    "b": [
      43.43,
      12.19,
      43.97,
      13.18
    ]
  },
  "ITPV": {
    "cc": "IT",
    "a": "ITPV",
    "n": "Pavia",
    "iso": "IT-PV",
    "la": 45.05,
    "lo": 9.03,
    "b": [
      44.68,
      8.5,
      45.41,
      9.55
    ]
  },
  "ITPZ": {
    "cc": "IT",
    "a": "ITPZ",
    "n": "Potenza",
    "iso": "IT-PZ",
    "la": 40.52,
    "lo": 15.87,
    "b": [
      39.9,
      15.34,
      41.14,
      16.4
    ]
  },
  "ITRA": {
    "cc": "IT",
    "a": "ITRA",
    "n": "Ravenna",
    "iso": "IT-RA",
    "la": 44.38,
    "lo": 11.96,
    "b": [
      44.12,
      11.53,
      44.63,
      12.39
    ]
  },
  "ITRC": {
    "cc": "IT",
    "a": "ITRC",
    "n": "Reggio Calabria",
    "iso": "IT-RC",
    "la": 38.25,
    "lo": 16.1,
    "b": [
      37.92,
      15.62,
      38.57,
      16.57
    ]
  },
  "ITRE": {
    "cc": "IT",
    "a": "ITRE",
    "n": "Reggio Emilia",
    "iso": "IT-RE",
    "la": 44.61,
    "lo": 10.52,
    "b": [
      44.22,
      10.14,
      44.99,
      10.89
    ]
  },
  "ITRG": {
    "cc": "IT",
    "a": "ITRG",
    "n": "Ragusa",
    "iso": "IT-RG",
    "la": 36.92,
    "lo": 14.67,
    "b": [
      36.69,
      14.33,
      37.14,
      15
    ]
  },
  "ITRI": {
    "cc": "IT",
    "a": "ITRI",
    "n": "Rieti",
    "iso": "IT-RI",
    "la": 42.42,
    "lo": 12.92,
    "b": [
      42.1,
      12.45,
      42.74,
      13.39
    ]
  },
  "ITRM": {
    "cc": "IT",
    "a": "ITRM",
    "n": "Roma",
    "iso": "IT-RM",
    "la": 41.86,
    "lo": 12.52,
    "b": [
      41.42,
      11.74,
      42.3,
      13.3
    ]
  },
  "ITRN": {
    "cc": "IT",
    "a": "ITRN",
    "n": "Rimini",
    "iso": "IT-RN",
    "la": 43.96,
    "lo": 12.43,
    "b": [
      43.74,
      12.1,
      44.17,
      12.75
    ]
  },
  "ITRO": {
    "cc": "IT",
    "a": "ITRO",
    "n": "Rovigo",
    "iso": "IT-RO",
    "la": 44.97,
    "lo": 11.86,
    "b": [
      44.79,
      11.19,
      45.16,
      12.53
    ]
  },
  "ITSA": {
    "cc": "IT",
    "a": "ITSA",
    "n": "Salerno",
    "iso": "IT-SA",
    "la": 40.42,
    "lo": 15.13,
    "b": [
      39.99,
      14.47,
      40.85,
      15.79
    ]
  },
  "ITSI": {
    "cc": "IT",
    "a": "ITSI",
    "n": "Siena",
    "iso": "IT-SI",
    "la": 43.18,
    "lo": 11.45,
    "b": [
      42.8,
      10.91,
      43.55,
      11.98
    ]
  },
  "ITSO": {
    "cc": "IT",
    "a": "ITSO",
    "n": "Sondrio",
    "iso": "IT-SO",
    "la": 46.32,
    "lo": 9.93,
    "b": [
      46.01,
      9.22,
      46.63,
      10.64
    ]
  },
  "ITSP": {
    "cc": "IT",
    "a": "ITSP",
    "n": "La Spezia",
    "iso": "IT-SP",
    "la": 44.24,
    "lo": 9.77,
    "b": [
      44.04,
      9.47,
      44.43,
      10.06
    ]
  },
  "ITSR": {
    "cc": "IT",
    "a": "ITSR",
    "n": "Siracusa",
    "iso": "IT-SR",
    "la": 37.03,
    "lo": 15.06,
    "b": [
      36.65,
      14.78,
      37.41,
      15.33
    ]
  },
  "ITSS": {
    "cc": "IT",
    "a": "ITSS",
    "n": "Sassari",
    "iso": "IT-SS",
    "la": 40.72,
    "lo": 8.71,
    "b": [
      40.31,
      8.13,
      41.13,
      9.28
    ]
  },
  "ITSV": {
    "cc": "IT",
    "a": "ITSV",
    "n": "Savona",
    "iso": "IT-SV",
    "la": 44.24,
    "lo": 8.32,
    "b": [
      43.94,
      7.98,
      44.53,
      8.67
    ]
  },
  "ITTA": {
    "cc": "IT",
    "a": "ITTA",
    "n": "Taranto",
    "iso": "IT-TA",
    "la": 40.53,
    "lo": 17.25,
    "b": [
      40.29,
      16.7,
      40.76,
      17.8
    ]
  },
  "ITTE": {
    "cc": "IT",
    "a": "ITTE",
    "n": "Teramo",
    "iso": "IT-TE",
    "la": 42.66,
    "lo": 13.75,
    "b": [
      42.42,
      13.34,
      42.9,
      14.15
    ]
  },
  "ITTN": {
    "cc": "IT",
    "a": "ITTN",
    "n": "Trento",
    "iso": "IT-TN",
    "la": 46.11,
    "lo": 11.22,
    "b": [
      45.68,
      10.46,
      46.53,
      11.97
    ]
  },
  "ITTO": {
    "cc": "IT",
    "a": "ITTO",
    "n": "Turin",
    "iso": "IT-TO",
    "la": 45.16,
    "lo": 7.38,
    "b": [
      44.71,
      6.6,
      45.6,
      8.15
    ]
  },
  "ITTP": {
    "cc": "IT",
    "a": "ITTP",
    "n": "Trapani",
    "iso": "IT-TP",
    "la": 37.47,
    "lo": 12.51,
    "b": [
      36.74,
      11.92,
      38.19,
      13.09
    ]
  },
  "ITTR": {
    "cc": "IT",
    "a": "ITTR",
    "n": "Terni",
    "iso": "IT-TR",
    "la": 42.66,
    "lo": 12.4,
    "b": [
      42.37,
      11.89,
      42.94,
      12.9
    ]
  },
  "ITTS": {
    "cc": "IT",
    "a": "ITTS",
    "n": "Trieste",
    "iso": "IT-TS",
    "la": 45.7,
    "lo": 13.74,
    "b": [
      45.58,
      13.58,
      45.81,
      13.89
    ]
  },
  "ITTV": {
    "cc": "IT",
    "a": "ITTV",
    "n": "Treviso",
    "iso": "IT-TV",
    "la": 45.81,
    "lo": 12.21,
    "b": [
      45.53,
      11.74,
      46.08,
      12.67
    ]
  },
  "ITUD": {
    "cc": "IT",
    "a": "ITUD",
    "n": "Udine",
    "iso": "IT-UD",
    "la": 46.15,
    "lo": 13.1,
    "b": [
      45.65,
      12.5,
      46.64,
      13.7
    ]
  },
  "ITVA": {
    "cc": "IT",
    "a": "ITVA",
    "n": "Varese",
    "iso": "IT-VA",
    "la": 45.84,
    "lo": 8.82,
    "b": [
      45.56,
      8.57,
      46.11,
      9.06
    ]
  },
  "ITVB": {
    "cc": "IT",
    "a": "ITVB",
    "n": "Verbano-Cusio-Ossola",
    "iso": "IT-VB",
    "la": 46.11,
    "lo": 8.29,
    "b": [
      45.77,
      7.85,
      46.45,
      8.73
    ]
  },
  "ITVC": {
    "cc": "IT",
    "a": "ITVC",
    "n": "Vercelli",
    "iso": "IT-VC",
    "la": 45.56,
    "lo": 8.21,
    "b": [
      45.16,
      7.85,
      45.95,
      8.56
    ]
  },
  "ITVE": {
    "cc": "IT",
    "a": "ITVE",
    "n": "Venezia",
    "iso": "IT-VE",
    "la": 45.46,
    "lo": 12.53,
    "b": [
      45.06,
      11.96,
      45.86,
      13.1
    ]
  },
  "ITVI": {
    "cc": "IT",
    "a": "ITVI",
    "n": "Vicenza",
    "iso": "IT-VI",
    "la": 45.63,
    "lo": 11.48,
    "b": [
      45.24,
      11.13,
      46.02,
      11.83
    ]
  },
  "ITVR": {
    "cc": "IT",
    "a": "ITVR",
    "n": "Verona",
    "iso": "IT-VR",
    "la": 45.44,
    "lo": 11.07,
    "b": [
      45.05,
      10.64,
      45.83,
      11.49
    ]
  },
  "ITVS": {
    "cc": "IT",
    "a": "ITVS",
    "n": "Medio Campidano",
    "iso": "IT-VS",
    "la": 39.58,
    "lo": 8.73,
    "b": [
      39.37,
      8.39,
      39.79,
      9.07
    ]
  },
  "ITVT": {
    "cc": "IT",
    "a": "ITVT",
    "n": "Viterbo",
    "iso": "IT-VT",
    "la": 42.5,
    "lo": 11.99,
    "b": [
      42.15,
      11.45,
      42.85,
      12.52
    ]
  },
  "ITVV": {
    "cc": "IT",
    "a": "ITVV",
    "n": "Vibo Valentia",
    "iso": "IT-VV",
    "la": 38.63,
    "lo": 16.13,
    "b": [
      38.43,
      15.83,
      38.83,
      16.43
    ]
  },
  "PT01": {
    "cc": "PT",
    "a": "PT01",
    "n": "Aveiro",
    "iso": "PT-01",
    "la": 40.69,
    "lo": -8.44,
    "b": [
      40.29,
      -8.79,
      41.08,
      -8.09
    ]
  },
  "PT02": {
    "cc": "PT",
    "a": "PT02",
    "n": "Beja",
    "iso": "PT-02",
    "la": 37.83,
    "lo": -7.89,
    "b": [
      37.33,
      -8.83,
      38.33,
      -6.95
    ]
  },
  "PT03": {
    "cc": "PT",
    "a": "PT03",
    "n": "Braga",
    "iso": "PT-03",
    "la": 41.58,
    "lo": -8.31,
    "b": [
      41.33,
      -8.82,
      41.82,
      -7.81
    ]
  },
  "PT04": {
    "cc": "PT",
    "a": "PT04",
    "n": "Bragança",
    "iso": "PT-04",
    "la": 41.52,
    "lo": -6.82,
    "b": [
      41.05,
      -7.43,
      41.99,
      -6.21
    ]
  },
  "PT05": {
    "cc": "PT",
    "a": "PT05",
    "n": "Castelo Branco",
    "iso": "PT-05",
    "la": 39.99,
    "lo": -7.58,
    "b": [
      39.56,
      -8.28,
      40.41,
      -6.88
    ]
  },
  "PT06": {
    "cc": "PT",
    "a": "PT06",
    "n": "Coimbra",
    "iso": "PT-06",
    "la": 40.22,
    "lo": -8.32,
    "b": [
      39.92,
      -8.91,
      40.52,
      -7.74
    ]
  },
  "PT07": {
    "cc": "PT",
    "a": "PT07",
    "n": "Évora",
    "iso": "PT-07",
    "la": 38.61,
    "lo": -7.88,
    "b": [
      38.18,
      -8.65,
      39.03,
      -7.12
    ]
  },
  "PT08": {
    "cc": "PT",
    "a": "PT08",
    "n": "Faro",
    "iso": "PT-08",
    "la": 37.25,
    "lo": -8.2,
    "b": [
      36.97,
      -9,
      37.53,
      -7.4
    ]
  },
  "PT09": {
    "cc": "PT",
    "a": "PT09",
    "n": "Guarda",
    "iso": "PT-09",
    "la": 40.71,
    "lo": -7.31,
    "b": [
      40.23,
      -7.84,
      41.19,
      -6.79
    ]
  },
  "PT10": {
    "cc": "PT",
    "a": "PT10",
    "n": "Leiria",
    "iso": "PT-10",
    "la": 39.66,
    "lo": -8.76,
    "b": [
      39.22,
      -9.41,
      40.09,
      -8.11
    ]
  },
  "PT11": {
    "cc": "PT",
    "a": "PT11",
    "n": "Lisboa",
    "iso": "PT-11",
    "la": 39,
    "lo": -9.14,
    "b": [
      38.67,
      -9.5,
      39.32,
      -8.79
    ]
  },
  "PT12": {
    "cc": "PT",
    "a": "PT12",
    "n": "Portalegre",
    "iso": "PT-12",
    "la": 39.23,
    "lo": -7.65,
    "b": [
      38.77,
      -8.33,
      39.68,
      -6.97
    ]
  },
  "PT13": {
    "cc": "PT",
    "a": "PT13",
    "n": "Porto",
    "iso": "PT-13",
    "la": 41.24,
    "lo": -8.33,
    "b": [
      41.01,
      -8.79,
      41.47,
      -7.88
    ]
  },
  "PT14": {
    "cc": "PT",
    "a": "PT14",
    "n": "Santarém",
    "iso": "PT-14",
    "la": 39.28,
    "lo": -8.4,
    "b": [
      38.73,
      -9,
      39.84,
      -7.8
    ]
  },
  "PT15": {
    "cc": "PT",
    "a": "PT15",
    "n": "Setúbal",
    "iso": "PT-15",
    "la": 38.3,
    "lo": -8.69,
    "b": [
      37.75,
      -9.25,
      38.84,
      -8.13
    ]
  },
  "PT16": {
    "cc": "PT",
    "a": "PT16",
    "n": "Viana do Castelo",
    "iso": "PT-16",
    "la": 41.89,
    "lo": -8.49,
    "b": [
      41.62,
      -8.88,
      42.15,
      -8.1
    ]
  },
  "PT17": {
    "cc": "PT",
    "a": "PT17",
    "n": "Vila Real",
    "iso": "PT-17",
    "la": 41.53,
    "lo": -7.64,
    "b": [
      41.15,
      -8.12,
      41.91,
      -7.17
    ]
  },
  "PT18": {
    "cc": "PT",
    "a": "PT18",
    "n": "Viseu",
    "iso": "PT-18",
    "la": 40.77,
    "lo": -7.82,
    "b": [
      40.32,
      -8.35,
      41.22,
      -7.3
    ]
  },
  "PT20": {
    "cc": "PT",
    "a": "PT20",
    "n": "Azores",
    "iso": "PT-20",
    "la": 38.33,
    "lo": -28.15,
    "b": [
      36.93,
      -31.28,
      39.73,
      -25.01
    ]
  },
  "PT30": {
    "cc": "PT",
    "a": "PT30",
    "n": "Madeira",
    "iso": "PT-30",
    "la": 31.57,
    "lo": -16.55,
    "b": [
      30.03,
      -17.25,
      33.11,
      -15.85
    ]
  },
  "AT1": {
    "cc": "AT",
    "a": "AT1",
    "n": "Burgenland",
    "iso": "AT-1",
    "la": 47.48,
    "lo": 16.58,
    "b": [
      46.84,
      16,
      48.11,
      17.15
    ]
  },
  "AT2": {
    "cc": "AT",
    "a": "AT2",
    "n": "Kärnten",
    "iso": "AT-2",
    "la": 46.76,
    "lo": 13.87,
    "b": [
      46.38,
      12.63,
      47.14,
      15.11
    ]
  },
  "AT3": {
    "cc": "AT",
    "a": "AT3",
    "n": "Niederösterreich",
    "iso": "AT-3",
    "la": 48.22,
    "lo": 15.75,
    "b": [
      47.44,
      14.43,
      49.01,
      17.06
    ]
  },
  "AT4": {
    "cc": "AT",
    "a": "AT4",
    "n": "Oberösterreich",
    "iso": "AT-4",
    "la": 48.12,
    "lo": 13.86,
    "b": [
      47.47,
      12.74,
      48.77,
      14.98
    ]
  },
  "AT5": {
    "cc": "AT",
    "a": "AT5",
    "n": "Salzburg",
    "iso": "AT-5",
    "la": 47.49,
    "lo": 13.01,
    "b": [
      46.95,
      12.08,
      48.03,
      13.94
    ]
  },
  "AT6": {
    "cc": "AT",
    "a": "AT6",
    "n": "Steiermark",
    "iso": "AT-6",
    "la": 47.22,
    "lo": 14.86,
    "b": [
      46.61,
      13.57,
      47.83,
      16.15
    ]
  },
  "AT7": {
    "cc": "AT",
    "a": "AT7",
    "n": "Tirol",
    "iso": "AT-7",
    "la": 47.19,
    "lo": 11.52,
    "b": [
      46.65,
      10.08,
      47.73,
      12.95
    ]
  },
  "AT8": {
    "cc": "AT",
    "a": "AT8",
    "n": "Vorarlberg",
    "iso": "AT-8",
    "la": 47.22,
    "lo": 9.87,
    "b": [
      46.85,
      9.52,
      47.59,
      10.21
    ]
  },
  "AT9": {
    "cc": "AT",
    "a": "AT9",
    "n": "Wien",
    "iso": "AT-9",
    "la": 48.24,
    "lo": 16.38,
    "b": [
      48.14,
      16.19,
      48.33,
      16.57
    ]
  },
  "CHAG": {
    "cc": "CH",
    "a": "CHAG",
    "n": "Aargau",
    "iso": "CH-AG",
    "la": 47.38,
    "lo": 8.09,
    "b": [
      47.14,
      7.73,
      47.62,
      8.45
    ]
  },
  "CHAI": {
    "cc": "CH",
    "a": "CHAI",
    "n": "Appenzell Innerrhoden",
    "iso": "CH-AI",
    "la": 47.35,
    "lo": 9.46,
    "b": [
      47.24,
      9.3,
      47.45,
      9.61
    ]
  },
  "CHAR": {
    "cc": "CH",
    "a": "CHAR",
    "n": "Appenzell Ausserrhoden",
    "iso": "CH-AR",
    "la": 47.36,
    "lo": 9.4,
    "b": [
      47.25,
      9.19,
      47.47,
      9.61
    ]
  },
  "CHBE": {
    "cc": "CH",
    "a": "CHBE",
    "n": "Bern",
    "iso": "CH-BE",
    "la": 46.84,
    "lo": 7.65,
    "b": [
      46.33,
      6.85,
      47.34,
      8.45
    ]
  },
  "CHBL": {
    "cc": "CH",
    "a": "CHBL",
    "n": "Basel-Landschaft",
    "iso": "CH-BL",
    "la": 47.45,
    "lo": 7.65,
    "b": [
      47.34,
      7.34,
      47.56,
      7.95
    ]
  },
  "CHBS": {
    "cc": "CH",
    "a": "CHBS",
    "n": "Basel-Stadt",
    "iso": "CH-BS",
    "la": 47.57,
    "lo": 7.59,
    "b": [
      47.53,
      7.52,
      47.6,
      7.66
    ]
  },
  "CHFR": {
    "cc": "CH",
    "a": "CHFR",
    "n": "Fribourg",
    "iso": "CH-FR",
    "la": 46.72,
    "lo": 7.07,
    "b": [
      46.44,
      6.76,
      47,
      7.38
    ]
  },
  "CHGE": {
    "cc": "CH",
    "a": "CHGE",
    "n": "Genève",
    "iso": "CH-GE",
    "la": 46.23,
    "lo": 6.12,
    "b": [
      46.13,
      5.95,
      46.33,
      6.28
    ]
  },
  "CHGL": {
    "cc": "CH",
    "a": "CHGL",
    "n": "Glarus",
    "iso": "CH-GL",
    "la": 46.99,
    "lo": 9.06,
    "b": [
      46.8,
      8.87,
      47.17,
      9.24
    ]
  },
  "CHGR": {
    "cc": "CH",
    "a": "CHGR",
    "n": "Graubünden",
    "iso": "CH-GR",
    "la": 46.62,
    "lo": 9.56,
    "b": [
      46.17,
      8.65,
      47.06,
      10.47
    ]
  },
  "CHJU": {
    "cc": "CH",
    "a": "CHJU",
    "n": "Jura",
    "iso": "CH-JU",
    "la": 47.33,
    "lo": 7.2,
    "b": [
      47.15,
      6.84,
      47.5,
      7.56
    ]
  },
  "CHLU": {
    "cc": "CH",
    "a": "CHLU",
    "n": "Lucerne",
    "iso": "CH-LU",
    "la": 47.03,
    "lo": 8.18,
    "b": [
      46.78,
      7.84,
      47.28,
      8.51
    ]
  },
  "CHNE": {
    "cc": "CH",
    "a": "CHNE",
    "n": "Neuchâtel",
    "iso": "CH-NE",
    "la": 47.01,
    "lo": 6.76,
    "b": [
      46.85,
      6.43,
      47.17,
      7.09
    ]
  },
  "CHNW": {
    "cc": "CH",
    "a": "CHNW",
    "n": "Nidwalden",
    "iso": "CH-NW",
    "la": 46.9,
    "lo": 8.39,
    "b": [
      46.78,
      8.22,
      47.01,
      8.56
    ]
  },
  "CHOW": {
    "cc": "CH",
    "a": "CHOW",
    "n": "Obwalden",
    "iso": "CH-OW",
    "la": 46.87,
    "lo": 8.27,
    "b": [
      46.76,
      8.04,
      46.98,
      8.5
    ]
  },
  "CHSG": {
    "cc": "CH",
    "a": "CHSG",
    "n": "Sankt Gallen",
    "iso": "CH-SG",
    "la": 47.21,
    "lo": 9.22,
    "b": [
      46.88,
      8.78,
      47.54,
      9.65
    ]
  },
  "CHSH": {
    "cc": "CH",
    "a": "CHSH",
    "n": "Schaffhausen",
    "iso": "CH-SH",
    "la": 47.68,
    "lo": 8.63,
    "b": [
      47.56,
      8.39,
      47.8,
      8.86
    ]
  },
  "CHSO": {
    "cc": "CH",
    "a": "CHSO",
    "n": "Solothurn",
    "iso": "CH-SO",
    "la": 47.29,
    "lo": 7.69,
    "b": [
      47.08,
      7.35,
      47.5,
      8.03
    ]
  },
  "CHSZ": {
    "cc": "CH",
    "a": "CHSZ",
    "n": "Schwyz",
    "iso": "CH-SZ",
    "la": 47.06,
    "lo": 8.69,
    "b": [
      46.89,
      8.39,
      47.22,
      8.99
    ]
  },
  "CHTG": {
    "cc": "CH",
    "a": "CHTG",
    "n": "Thurgau",
    "iso": "CH-TG",
    "la": 47.53,
    "lo": 9.15,
    "b": [
      47.38,
      8.74,
      47.68,
      9.55
    ]
  },
  "CHTI": {
    "cc": "CH",
    "a": "CHTI",
    "n": "Ticino",
    "iso": "CH-TI",
    "la": 46.23,
    "lo": 8.77,
    "b": [
      45.82,
      8.38,
      46.63,
      9.16
    ]
  },
  "CHUR": {
    "cc": "CH",
    "a": "CHUR",
    "n": "Uri",
    "iso": "CH-UR",
    "la": 46.76,
    "lo": 8.68,
    "b": [
      46.53,
      8.4,
      46.99,
      8.95
    ]
  },
  "CHVD": {
    "cc": "CH",
    "a": "CHVD",
    "n": "Vaud",
    "iso": "CH-VD",
    "la": 46.59,
    "lo": 6.65,
    "b": [
      46.19,
      6.05,
      46.99,
      7.25
    ]
  },
  "CHVS": {
    "cc": "CH",
    "a": "CHVS",
    "n": "Valais",
    "iso": "CH-VS",
    "la": 46.27,
    "lo": 7.62,
    "b": [
      45.88,
      6.75,
      46.66,
      8.48
    ]
  },
  "CHZG": {
    "cc": "CH",
    "a": "CHZG",
    "n": "Zug",
    "iso": "CH-ZG",
    "la": 47.17,
    "lo": 8.55,
    "b": [
      47.09,
      8.39,
      47.25,
      8.7
    ]
  },
  "CHZH": {
    "cc": "CH",
    "a": "CHZH",
    "n": "Zürich",
    "iso": "CH-ZH",
    "la": 47.43,
    "lo": 8.66,
    "b": [
      47.16,
      8.35,
      47.7,
      8.97
    ]
  },
  "SEAB": {
    "cc": "SE",
    "a": "SEAB",
    "n": "Stockholm",
    "iso": "SE-AB",
    "la": 59.54,
    "lo": 18.19,
    "b": [
      58.86,
      17.28,
      60.22,
      19.09
    ]
  },
  "SEAC": {
    "cc": "SE",
    "a": "SEAC",
    "n": "Västerbotten",
    "iso": "SE-AC",
    "la": 64.88,
    "lo": 17.97,
    "b": [
      63.41,
      14.33,
      66.35,
      21.61
    ]
  },
  "SEBD": {
    "cc": "SE",
    "a": "SEBD",
    "n": "Norrbotten",
    "iso": "SE-BD",
    "la": 67.06,
    "lo": 19.8,
    "b": [
      65.07,
      15.43,
      69.04,
      24.16
    ]
  },
  "SEC": {
    "cc": "SE",
    "a": "SEC",
    "n": "Uppsala",
    "iso": "SE-C",
    "la": 60.02,
    "lo": 17.7,
    "b": [
      59.39,
      16.79,
      60.65,
      18.6
    ]
  },
  "SED": {
    "cc": "SE",
    "a": "SED",
    "n": "Södermanland",
    "iso": "SE-D",
    "la": 59.08,
    "lo": 16.63,
    "b": [
      58.63,
      15.64,
      59.53,
      17.63
    ]
  },
  "SEE": {
    "cc": "SE",
    "a": "SEE",
    "n": "Östergötland",
    "iso": "SE-E",
    "la": 58.36,
    "lo": 15.69,
    "b": [
      57.71,
      14.43,
      59.01,
      16.94
    ]
  },
  "SEF": {
    "cc": "SE",
    "a": "SEF",
    "n": "Jönköping",
    "iso": "SE-F",
    "la": 57.56,
    "lo": 14.38,
    "b": [
      56.89,
      13.09,
      58.22,
      15.67
    ]
  },
  "SEG": {
    "cc": "SE",
    "a": "SEG",
    "n": "Kronoberg",
    "iso": "SE-G",
    "la": 56.81,
    "lo": 14.58,
    "b": [
      56.38,
      13.31,
      57.24,
      15.85
    ]
  },
  "SEH": {
    "cc": "SE",
    "a": "SEH",
    "n": "Kalmar",
    "iso": "SE-H",
    "la": 57.18,
    "lo": 16.24,
    "b": [
      56.22,
      15.36,
      58.13,
      17.12
    ]
  },
  "SEI": {
    "cc": "SE",
    "a": "SEI",
    "n": "Gotland",
    "iso": "SE-I",
    "la": 57.66,
    "lo": 18.72,
    "b": [
      56.91,
      18.1,
      58.4,
      19.34
    ]
  },
  "SEK": {
    "cc": "SE",
    "a": "SEK",
    "n": "Blekinge",
    "iso": "SE-K",
    "la": 56.26,
    "lo": 15.24,
    "b": [
      56,
      14.41,
      56.51,
      16.07
    ]
  },
  "SEM": {
    "cc": "SE",
    "a": "SEM",
    "n": "Skåne",
    "iso": "SE-M",
    "la": 55.94,
    "lo": 13.52,
    "b": [
      55.34,
      12.45,
      56.54,
      14.59
    ]
  },
  "SEN": {
    "cc": "SE",
    "a": "SEN",
    "n": "Halland",
    "iso": "SE-N",
    "la": 56.98,
    "lo": 12.8,
    "b": [
      56.34,
      11.9,
      57.62,
      13.7
    ]
  },
  "SEO": {
    "cc": "SE",
    "a": "SEO",
    "n": "Västra Götaland",
    "iso": "SE-O",
    "la": 58.21,
    "lo": 12.96,
    "b": [
      57.16,
      11.11,
      59.25,
      14.81
    ]
  },
  "SES": {
    "cc": "SE",
    "a": "SES",
    "n": "Värmland",
    "iso": "SE-S",
    "la": 59.9,
    "lo": 13.08,
    "b": [
      58.74,
      11.67,
      61.06,
      14.48
    ]
  },
  "SET": {
    "cc": "SE",
    "a": "SET",
    "n": "Orebro",
    "iso": "SE-T",
    "la": 59.39,
    "lo": 15.06,
    "b": [
      58.65,
      14.31,
      60.12,
      15.81
    ]
  },
  "SEU": {
    "cc": "SE",
    "a": "SEU",
    "n": "Västmanland",
    "iso": "SE-U",
    "la": 59.76,
    "lo": 16.42,
    "b": [
      59.21,
      15.45,
      60.31,
      17.39
    ]
  },
  "SEW": {
    "cc": "SE",
    "a": "SEW",
    "n": "Dalarna",
    "iso": "SE-W",
    "la": 61.08,
    "lo": 14.44,
    "b": [
      59.88,
      12.16,
      62.27,
      16.72
    ]
  },
  "SEX": {
    "cc": "SE",
    "a": "SEX",
    "n": "Gävleborg",
    "iso": "SE-X",
    "la": 61.29,
    "lo": 16,
    "b": [
      60.21,
      14.48,
      62.36,
      17.52
    ]
  },
  "SEY": {
    "cc": "SE",
    "a": "SEY",
    "n": "Västernorrland",
    "iso": "SE-Y",
    "la": 63.08,
    "lo": 17.07,
    "b": [
      62.15,
      14.82,
      64.02,
      19.32
    ]
  },
  "SEZ": {
    "cc": "SE",
    "a": "SEZ",
    "n": "Jämtland",
    "iso": "SE-Z",
    "la": 63.35,
    "lo": 14.48,
    "b": [
      61.58,
      11.99,
      65.11,
      16.97
    ]
  },
  "NO01": {
    "cc": "NO",
    "a": "NO01",
    "n": "Østfold",
    "iso": "NO-01",
    "la": 59.35,
    "lo": 11.25,
    "b": [
      58.88,
      10.59,
      59.81,
      11.9
    ]
  },
  "NO02": {
    "cc": "NO",
    "a": "NO02",
    "n": "Akershus",
    "iso": "NO-02",
    "la": 60.05,
    "lo": 11.22,
    "b": [
      59.48,
      10.56,
      60.62,
      11.88
    ]
  },
  "NO03": {
    "cc": "NO",
    "a": "NO03",
    "n": "Oslo",
    "iso": "NO-03",
    "la": 59.97,
    "lo": 10.64,
    "b": [
      59.8,
      10.35,
      60.15,
      10.93
    ]
  },
  "NO04": {
    "cc": "NO",
    "a": "NO04",
    "n": "Hedmark",
    "iso": "NO-04",
    "la": 61.3,
    "lo": 11.28,
    "b": [
      59.88,
      9.66,
      62.71,
      12.89
    ]
  },
  "NO05": {
    "cc": "NO",
    "a": "NO05",
    "n": "Oppland",
    "iso": "NO-05",
    "la": 61.27,
    "lo": 9.25,
    "b": [
      60.15,
      7.33,
      62.39,
      11.16
    ]
  },
  "NO06": {
    "cc": "NO",
    "a": "NO06",
    "n": "Buskerud",
    "iso": "NO-06",
    "la": 60.28,
    "lo": 9.05,
    "b": [
      59.43,
      7.47,
      61.12,
      10.62
    ]
  },
  "NO07": {
    "cc": "NO",
    "a": "NO07",
    "n": "Vestfold",
    "iso": "NO-07",
    "la": 59.33,
    "lo": 10.14,
    "b": [
      58.96,
      9.77,
      59.7,
      10.51
    ]
  },
  "NO08": {
    "cc": "NO",
    "a": "NO08",
    "n": "Telemark",
    "iso": "NO-08",
    "la": 59.49,
    "lo": 8.49,
    "b": [
      58.78,
      7.09,
      60.2,
      9.88
    ]
  },
  "NO09": {
    "cc": "NO",
    "a": "NO09",
    "n": "Aust-Agder",
    "iso": "NO-09",
    "la": 58.93,
    "lo": 8.11,
    "b": [
      58.16,
      6.82,
      59.69,
      9.39
    ]
  },
  "NO10": {
    "cc": "NO",
    "a": "NO10",
    "n": "Vest-Agder",
    "iso": "NO-10",
    "la": 58.6,
    "lo": 7.32,
    "b": [
      57.99,
      6.4,
      59.21,
      8.23
    ]
  },
  "NO11": {
    "cc": "NO",
    "a": "NO11",
    "n": "Rogaland",
    "iso": "NO-11",
    "la": 59.07,
    "lo": 6.2,
    "b": [
      58.27,
      5.16,
      59.86,
      7.24
    ]
  },
  "NO12": {
    "cc": "NO",
    "a": "NO12",
    "n": "Hordaland",
    "iso": "NO-12",
    "la": 60.26,
    "lo": 6.23,
    "b": [
      59.48,
      4.78,
      61.03,
      7.68
    ]
  },
  "NO14": {
    "cc": "NO",
    "a": "NO14",
    "n": "Sogn og Fjordane",
    "iso": "NO-14",
    "la": 61.46,
    "lo": 6.48,
    "b": [
      60.7,
      4.64,
      62.21,
      8.31
    ]
  },
  "NO15": {
    "cc": "NO",
    "a": "NO15",
    "n": "Møre og Romsdal",
    "iso": "NO-15",
    "la": 62.72,
    "lo": 7.49,
    "b": [
      61.96,
      5.39,
      63.47,
      9.58
    ]
  },
  "NO16": {
    "cc": "NO",
    "a": "NO16",
    "n": "Sør-Trøndelag",
    "iso": "NO-16",
    "la": 63.35,
    "lo": 10.27,
    "b": [
      62.27,
      8.27,
      64.43,
      12.28
    ]
  },
  "NO17": {
    "cc": "NO",
    "a": "NO17",
    "n": "Nord-Trøndelag",
    "iso": "NO-17",
    "la": 64.16,
    "lo": 12.25,
    "b": [
      63.2,
      10.16,
      65.13,
      14.33
    ]
  },
  "NO18": {
    "cc": "NO",
    "a": "NO18",
    "n": "Nordland",
    "iso": "NO-18",
    "la": 68.07,
    "lo": 4.54,
    "b": [
      64.95,
      -9.12,
      71.18,
      18.19
    ]
  },
  "NO19": {
    "cc": "NO",
    "a": "NO19",
    "n": "Troms",
    "iso": "NO-19",
    "la": 69.32,
    "lo": 19.29,
    "b": [
      68.35,
      15.64,
      70.29,
      22.93
    ]
  },
  "NO20": {
    "cc": "NO",
    "a": "NO20",
    "n": "Finnmark",
    "iso": "NO-20",
    "la": 69.86,
    "lo": 26.16,
    "b": [
      68.55,
      21.23,
      71.17,
      31.08
    ]
  },
  "NO21": {
    "cc": "NO",
    "a": "NO21",
    "n": "Svalbard",
    "iso": "NO-21",
    "la": 77.56,
    "lo": 22.06,
    "b": [
      74.35,
      10.48,
      80.77,
      33.64
    ]
  },
  "DK81": {
    "cc": "DK",
    "a": "DK81",
    "n": "Nordjylland",
    "iso": "DK-81",
    "la": 57.16,
    "lo": 9.72,
    "b": [
      56.56,
      8.24,
      57.75,
      11.2
    ]
  },
  "DK82": {
    "cc": "DK",
    "a": "DK82",
    "n": "Midtjylland",
    "iso": "DK-82",
    "la": 56.24,
    "lo": 9.88,
    "b": [
      55.67,
      8.1,
      56.81,
      11.65
    ]
  },
  "DK83": {
    "cc": "DK",
    "a": "DK83",
    "n": "Syddanmark",
    "iso": "DK-83",
    "la": 55.34,
    "lo": 9.53,
    "b": [
      54.74,
      8.09,
      55.94,
      10.96
    ]
  },
  "DK84": {
    "cc": "DK",
    "a": "DK84",
    "n": "Hovedstaden",
    "iso": "DK-84",
    "la": 55.56,
    "lo": 13.5,
    "b": [
      54.99,
      11.84,
      56.13,
      15.15
    ]
  },
  "DK85": {
    "cc": "DK",
    "a": "DK85",
    "n": "Sjaælland",
    "iso": "DK-85",
    "la": 55.29,
    "lo": 11.72,
    "b": [
      54.57,
      10.88,
      56,
      12.55
    ]
  },
  "FI02": {
    "cc": "FI",
    "a": "FI02",
    "n": "South Karelia",
    "iso": "FI-02",
    "la": 61.26,
    "lo": 28.56,
    "b": [
      60.66,
      26.97,
      61.85,
      30.15
    ]
  },
  "FI03": {
    "cc": "FI",
    "a": "FI03",
    "n": "Southern Ostrobothnia",
    "iso": "FI-03",
    "la": 62.74,
    "lo": 23.06,
    "b": [
      61.99,
      21.53,
      63.49,
      24.58
    ]
  },
  "FI04": {
    "cc": "FI",
    "a": "FI04",
    "n": "Southern Savonia",
    "iso": "FI-04",
    "la": 61.9,
    "lo": 27.97,
    "b": [
      61.15,
      26.24,
      62.65,
      29.69
    ]
  },
  "FI05": {
    "cc": "FI",
    "a": "FI05",
    "n": "Kainuu",
    "iso": "FI-05",
    "la": 64.6,
    "lo": 28.45,
    "b": [
      63.68,
      26.3,
      65.52,
      30.59
    ]
  },
  "FI06": {
    "cc": "FI",
    "a": "FI06",
    "n": "Tavastia Proper",
    "iso": "FI-06",
    "la": 60.94,
    "lo": 24.22,
    "b": [
      60.55,
      23.14,
      61.32,
      25.29
    ]
  },
  "FI07": {
    "cc": "FI",
    "a": "FI07",
    "n": "Central Ostrobothnia",
    "iso": "FI-07",
    "la": 63.65,
    "lo": 24.01,
    "b": [
      63.12,
      22.99,
      64.17,
      25.03
    ]
  },
  "FI08": {
    "cc": "FI",
    "a": "FI08",
    "n": "Central Finland",
    "iso": "FI-08",
    "la": 62.53,
    "lo": 25.4,
    "b": [
      61.45,
      24.02,
      63.6,
      26.77
    ]
  },
  "FI09": {
    "cc": "FI",
    "a": "FI09",
    "n": "Kymenlaakso",
    "iso": "FI-09",
    "la": 60.84,
    "lo": 27.02,
    "b": [
      60.38,
      26.04,
      61.29,
      28
    ]
  },
  "FI10": {
    "cc": "FI",
    "a": "FI10",
    "n": "Lapland",
    "iso": "FI-10",
    "la": 67.84,
    "lo": 25.32,
    "b": [
      65.59,
      20.62,
      70.08,
      30.01
    ]
  },
  "FI11": {
    "cc": "FI",
    "a": "FI11",
    "n": "Pirkanmaa",
    "iso": "FI-11",
    "la": 61.72,
    "lo": 23.78,
    "b": [
      60.95,
      22.55,
      62.49,
      25
    ]
  },
  "FI12": {
    "cc": "FI",
    "a": "FI12",
    "n": "Ostrobothnia",
    "iso": "FI-12",
    "la": 62.87,
    "lo": 22.4,
    "b": [
      61.94,
      21.07,
      63.8,
      23.73
    ]
  },
  "FI13": {
    "cc": "FI",
    "a": "FI13",
    "n": "North Karelia",
    "iso": "FI-13",
    "la": 62.8,
    "lo": 29.97,
    "b": [
      61.72,
      28.36,
      63.88,
      31.57
    ]
  },
  "FI14": {
    "cc": "FI",
    "a": "FI14",
    "n": "Northern Ostrobothnia",
    "iso": "FI-14",
    "la": 64.96,
    "lo": 26.92,
    "b": [
      63.43,
      23.71,
      66.48,
      30.12
    ]
  },
  "FI15": {
    "cc": "FI",
    "a": "FI15",
    "n": "Northern Savonia",
    "iso": "FI-15",
    "la": 63.15,
    "lo": 27.57,
    "b": [
      62.26,
      26.05,
      64.03,
      29.09
    ]
  },
  "FI16": {
    "cc": "FI",
    "a": "FI16",
    "n": "Päijät-Häme",
    "iso": "FI-16",
    "la": 61.25,
    "lo": 25.69,
    "b": [
      60.69,
      24.86,
      61.8,
      26.52
    ]
  },
  "FI17": {
    "cc": "FI",
    "a": "FI17",
    "n": "Satakunta",
    "iso": "FI-17",
    "la": 61.6,
    "lo": 22.16,
    "b": [
      60.89,
      21.32,
      62.3,
      23
    ]
  },
  "FI18": {
    "cc": "FI",
    "a": "FI18",
    "n": "Uusimaa",
    "iso": "FI-18",
    "la": 60.32,
    "lo": 24.72,
    "b": [
      59.81,
      22.89,
      60.83,
      26.55
    ]
  },
  "FI19": {
    "cc": "FI",
    "a": "FI19",
    "n": "Finland Proper",
    "iso": "FI-19",
    "la": 60.47,
    "lo": 22.55,
    "b": [
      59.85,
      21.19,
      61.09,
      23.91
    ]
  },
  "PLDS": {
    "cc": "PL",
    "a": "PLDS",
    "n": "Lower Silesian",
    "iso": "PL-DS",
    "la": 50.93,
    "lo": 16.27,
    "b": [
      50.09,
      14.81,
      51.77,
      17.72
    ]
  },
  "PLKP": {
    "cc": "PL",
    "a": "PLKP",
    "n": "Kuyavian-Pomeranian",
    "iso": "PL-KP",
    "la": 52.99,
    "lo": 18.52,
    "b": [
      52.28,
      17.3,
      53.7,
      19.75
    ]
  },
  "PLLB": {
    "cc": "PL",
    "a": "PLLB",
    "n": "Lubusz",
    "iso": "PL-LB",
    "la": 52.26,
    "lo": 15.46,
    "b": [
      51.4,
      14.54,
      53.11,
      16.37
    ]
  },
  "PLLD": {
    "cc": "PL",
    "a": "PLLD",
    "n": "Łódź",
    "iso": "PL-LD",
    "la": 51.57,
    "lo": 19.36,
    "b": [
      50.8,
      18.05,
      52.33,
      20.67
    ]
  },
  "PLLU": {
    "cc": "PL",
    "a": "PLLU",
    "n": "Lublin",
    "iso": "PL-LU",
    "la": 51.31,
    "lo": 22.9,
    "b": [
      50.31,
      21.65,
      52.3,
      24.14
    ]
  },
  "PLMA": {
    "cc": "PL",
    "a": "PLMA",
    "n": "Lesser Poland",
    "iso": "PL-MA",
    "la": 49.83,
    "lo": 20.31,
    "b": [
      49.17,
      19.11,
      50.48,
      21.51
    ]
  },
  "PLMZ": {
    "cc": "PL",
    "a": "PLMZ",
    "n": "Masovian",
    "iso": "PL-MZ",
    "la": 52.22,
    "lo": 21.2,
    "b": [
      51.01,
      19.3,
      53.44,
      23.09
    ]
  },
  "PLOP": {
    "cc": "PL",
    "a": "PLOP",
    "n": "Opole",
    "iso": "PL-OP",
    "la": 50.56,
    "lo": 17.8,
    "b": [
      49.97,
      16.94,
      51.15,
      18.66
    ]
  },
  "PLPD": {
    "cc": "PL",
    "a": "PLPD",
    "n": "Podlachian",
    "iso": "PL-PD",
    "la": 53.34,
    "lo": 22.72,
    "b": [
      52.28,
      21.52,
      54.4,
      23.92
    ]
  },
  "PLPK": {
    "cc": "PL",
    "a": "PLPK",
    "n": "Subcarpathian",
    "iso": "PL-PK",
    "la": 49.91,
    "lo": 22.44,
    "b": [
      48.99,
      21.21,
      50.83,
      23.66
    ]
  },
  "PLPM": {
    "cc": "PL",
    "a": "PLPM",
    "n": "Pomeranian",
    "iso": "PL-PM",
    "la": 54.14,
    "lo": 18.27,
    "b": [
      53.43,
      16.79,
      54.84,
      19.76
    ]
  },
  "PLSK": {
    "cc": "PL",
    "a": "PLSK",
    "n": "Świętokrzyskie",
    "iso": "PL-SK",
    "la": 50.73,
    "lo": 20.8,
    "b": [
      50.17,
      19.74,
      51.29,
      21.85
    ]
  },
  "PLSL": {
    "cc": "PL",
    "a": "PLSL",
    "n": "Silesian",
    "iso": "PL-SL",
    "la": 50.22,
    "lo": 18.99,
    "b": [
      49.39,
      18.02,
      51.04,
      19.97
    ]
  },
  "PLWN": {
    "cc": "PL",
    "a": "PLWN",
    "n": "Warmian-Masurian",
    "iso": "PL-WN",
    "la": 53.76,
    "lo": 20.97,
    "b": [
      53.09,
      19.13,
      54.43,
      22.81
    ]
  },
  "PLWP": {
    "cc": "PL",
    "a": "PLWP",
    "n": "Greater Poland",
    "iso": "PL-WP",
    "la": 52.34,
    "lo": 17.45,
    "b": [
      51.07,
      15.83,
      53.6,
      19.08
    ]
  },
  "PLZP": {
    "cc": "PL",
    "a": "PLZP",
    "n": "West Pomeranian",
    "iso": "PL-ZP",
    "la": 53.59,
    "lo": 15.59,
    "b": [
      52.6,
      14.12,
      54.58,
      17.06
    ]
  },
  "AUACT": {
    "cc": "AU",
    "a": "AUACT",
    "n": "Australian Capital Territory",
    "iso": "AU-ACT",
    "la": -35.53,
    "lo": 149.09,
    "b": [
      -35.91,
      148.77,
      -35.15,
      149.4
    ]
  },
  "AUNSW": {
    "cc": "AU",
    "a": "AUNSW",
    "n": "New South Wales",
    "iso": "AU-NSW",
    "la": -32.82,
    "lo": 147.31,
    "b": [
      -37.5,
      141,
      -28.14,
      153.62
    ]
  },
  "AUNT": {
    "cc": "AU",
    "a": "AUNT",
    "n": "Northern Territory",
    "iso": "AU-NT",
    "la": -18.48,
    "lo": 133.5,
    "b": [
      -26,
      129,
      -10.97,
      138
    ]
  },
  "AUQLD": {
    "cc": "AU",
    "a": "AUQLD",
    "n": "Queensland",
    "iso": "AU-QLD",
    "la": -19.59,
    "lo": 145.77,
    "b": [
      -29.14,
      138,
      -10.05,
      153.54
    ]
  },
  "AUSA": {
    "cc": "AU",
    "a": "AUSA",
    "n": "South Australia",
    "iso": "AU-SA",
    "la": -32.03,
    "lo": 135.01,
    "b": [
      -38.07,
      129,
      -26,
      141.03
    ]
  },
  "AUTAS": {
    "cc": "AU",
    "a": "AUTAS",
    "n": "Tasmania",
    "iso": "AU-TAS",
    "la": -41.6,
    "lo": 146.16,
    "b": [
      -43.62,
      143.84,
      -39.58,
      148.47
    ]
  },
  "AUVIC": {
    "cc": "AU",
    "a": "AUVIC",
    "n": "Victoria",
    "iso": "AU-VIC",
    "la": -36.58,
    "lo": 145.45,
    "b": [
      -39.15,
      140.97,
      -34.01,
      149.94
    ]
  },
  "AUWA": {
    "cc": "AU",
    "a": "AUWA",
    "n": "Western Australia",
    "iso": "AU-WA",
    "la": -24.42,
    "lo": 120.96,
    "b": [
      -35.1,
      112.91,
      -13.74,
      129
    ]
  }
};
